In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\Parsa\Downloads\retraction_watch.csv")

In [4]:
unique_subjects = df['Subject'].unique()

In [5]:
unique_subjects

array(['(B/T) Computer Science;(B/T) Data Science;(B/T) Technology;(SOC) Sports and Recreation;',
       '(B/T) Business - Manufacturing;(B/T) Computer Science;(B/T) Technology;(PHY) Engineering - Mechanical;',
       '(B/T) Business - Manufacturing;(B/T) Computer Science;(B/T) Data Science;(B/T) Technology;',
       ...,
       '(BLS) Biochemistry;(BLS) Biology - Molecular;(HSC) Medicine - Pulmonology;(HSC) Veterinary Science;',
       '(BLS) Biology - Molecular;(HSC) Medicine - Pulmonology;(HSC) Veterinary Science;',
       '(BLS) Biochemistry;(HSC) Medicine - Cardiology;(HSC) Medicine - Cardiovascular;(HSC) Medicine - Drug Design;(HSC) Medicine - Pharmacology;'],
      dtype=object)

In [6]:
df['Subject'].drop_duplicates()

0        (B/T) Computer Science;(B/T) Data Science;(B/T...
1        (B/T) Business - Manufacturing;(B/T) Computer ...
2        (B/T) Business - Manufacturing;(B/T) Computer ...
3        (B/T) Business - Manufacturing;(B/T) Computer ...
4        (B/T) Business - Economics;(B/T) Computer Scie...
                               ...
60699    (BLS) Biology - Cellular;(HSC) Medicine - Gast...
60700    (BLS) Biochemistry;(BLS) Biology - Cellular;(H...
60726    (BLS) Biochemistry;(BLS) Biology - Molecular;(...
60727    (BLS) Biology - Molecular;(HSC) Medicine - Pul...
60728    (BLS) Biochemistry;(HSC) Medicine - Cardiology...
Name: Subject, Length: 15044, dtype: object

In [3]:
iran_articles = df[df['Country'].str.contains('Iran', case=False, na=False)]

In [4]:
iran_articles[iran_articles['Subject'].str.contains('computer science', case=False, na=False)]

,Record ID,Title,Subject,Institution,Journal,Publisher,Country,Author,URLS,ArticleType,RetractionDate,RetractionDOI,RetractionPubMedID,OriginalPaperDate,OriginalPaperDOI,OriginalPaperPubMedID,RetractionNature,Reason,Paywalled,Notes
646,60474,Clustering of Brain Tumor Based on Analysis of...,(B/T) Computer Science;(B/T) Technology;(HSC) ...,"Department of Industrial Engineering, Islamic ...",BioMed Research International,Hindawi,Iran,Ali Hamzenejad;Saeid Jafarzadeh Ghoushchi;Vahi...,https://retractionwatch.com/2022/09/28/exclusi...,Research Article;,11/29/2023 0:00,10.1155/2023/9859342,38075360.0,8/31/2021 0:00,10.1155/2021/5516819,34504897.0,Retraction,+Fake Peer Review;+Investigation by Journal/Pu...,No,NaN
871,60249,Using a Blur Metric to Estimate Linear Motion ...,(B/T) Computer Science;(HSC) Radiology/Imaging;,"Computer Science Department, Faculty of Mathem...",Computational and Mathematical Methods in Medi...,Hindawi,Iran,Taiebeh Askari Javaran;Hamid Hassanpour,https://retractionwatch.com/2022/09/28/exclusi...,Research Article;,12/6/2023 0:00,10.1155/2023/9849356,38094468.0,10/28/2021 0:00,10.1155/2021/6048137,34745327.0,Retraction,+Fake Peer Review;+Investigation by Journal/Pu...,No,NaN
1076,60044,Method of Cumulative Anomaly Identification fo...,(B/T) Computer Science;(B/T) Technology;,"Shaoxing University Yuanpei College, Shaoxing ...",Security and Communication Networks,Hindawi,China;Iran,Zhiying Xu;Ting Yang;Moslem Lari Najafi,https://retractionwatch.com/2022/09/28/exclusi...,Research Article;,12/6/2023 0:00,10.1155/2023/9831958,0.0,3/21/2022 0:00,10.1155/2022/5113725,0.0,Retraction,+Fake Peer Review;+Investigation by Journal/Pu...,No,NaN
1452,59668,A secure remote health monitoring model for ea...,(B/T) Computer Science;(B/T) Technology;(HSC) ...,"Department of Computer Engineering, Science an...",Personal and Ubiquitous Computing,Springer,Iran;Vietnam,Samira Akhbarifar;Hamid Haj Seyyed Javadi;Amir...,NaN,Research Article;,12/14/2024 0:00,10.1007/s00779-024-01841-5,0.0,11/16/2020 0:00,10.1007/s00779-020-01475-3,33223984.0,Retraction,+Concerns/Issues About Results;+Concerns/Issue...,No,NaN
2432,58685,A-COA: an adaptive cuckoo optimization algorit...,(B/T) Computer Science;,Sama Technical and Vocational Training College...,Neural Computing and Applications,Springer,Egypt;Iran,H R Boveiri;M Elhoseny,NaN,Research Article;,4/24/2024 0:00,10.1007/s00521-024-09872-y,0.0,12/15/2018 0:00,10.1007/s00521-018-3928-9,0.0,Retraction,+Concerns/Issues About Results;+Concerns/Issue...,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53850,7034,A Novel Voting Mathematical Rule Classificatio...,(B/T) Computer Science;(PHY) Mathematics;,"Department of Computer Engineering, Iran Healt...",Lecture Notes in Computer Science,Springer,Iran,Sadrollah Abbasi;Afshin Shahriari;Yaser Nemati,NaN,Book Chapter/Reference Work;,12/27/2016 0:00,10.1007/978-3-319-42092-9_48,NaN,7/1/2016 0:00,10.1007/978-3-319-42092-9_20,NaN,Retraction,+Plagiarism of Article;,No,International Conference on Computational Scie...
53853,7031,Pose invariant face recognition using biologic...,(B/T) Computer Science;(B/T) Data Science;,"Faculty of Electrical Engineering, Iran Univer...",Journal of Visual Communication and Image Repr...,Elsevier,Iran,Masoud Ghaderi Dehkordi;Mohammad Reza Daliri;A...,http://retractionwatch.com/2015/06/22/plagiari...,Research Article;,5/26/2014 0:00,10.1016/j.jvcir.2014.05.007,0.0,6/18/2013 0:00,10.1016/j.jvcir.2013.06.007,0.0,Retraction,+Breach of Policy by Author;+Plagiarism of Art...,No,NaN
53953,6929,Fuzzy PID Sliding Mode Controller Design for t...,(B/T) Computer Science;(B/T) Technology;(PHY) ...,"Department of Mechatronics Engineering, Semnan...",2009 International Conference on Education Tec...,IEEE: Institute of Electrical and Electronics ...,Iran,Mohsen Fallahi;Sassan Azadi,https://retractionwatch.com/2015/06/25/one-pub...,Conference Abstract/Paper;,7/21/2009 0:00,10.1109/ICETC.2009.12,0.0,4/17/2009 0:00,10.1109/ICETC.2009.12,0.0,Retraction,+Breach of Policy by Author;+Date of Retractio...,No,"Date of retraction unknown, estimated from con..."
55250,5610,A Lagrangian-based Solution Algorithm for Stra...,(B/T) Business - Marketing;(B/T) Computer Scie...,"Department of Industrial Engineering, Amirkabi...",International Journal of Information Technolog...,World Scientific Publishing Company,Iran,G Reza Nasiri;Hamid Davoudpour;Behrooz Karimi,NaN,Research Article;,1/1/2013 0:00,10.1142/S0219622013930012,0.0,5/1/2010 0:00,10.1142/S0219622010003877,0.0,Retraction,+Duplication of Article;,Yes,NaN
56237,4600,A novel real-time patient-specific seizure dia...,(B/T) Computer Science;(HSC) Radiology/Imaging;,"Department of Electrical Engineering, Najafaba...",Computers in Biology and Medicine,Elsevier,Iran,Saadat Nasehi;Hossein Pourghassem,http://retractionwatch.com/2013/01/17/note-to-...,Research Article;,3/1/2013 0:00,10.1016/j.compbiomed.2012.06.008,23520624.0,7/15/2012 0:00,NaN,22795227.0,Retraction,+Concerns/Issues About Results;+Plagiarism of ...,No,NaN

In [15]:
import requests

API_KEY = "10a6fa24e6beeef124888369a691d5aa"
BASE_URL = "https://api.crossref.org/works/"

# Test DOI
doi = "10.1155/2023/9834646"

# Make a single API request
response = requests.get(f"{BASE_URL}{doi}", headers={"X-ELS-APIKey": API_KEY})

if response.status_code == 200:
    print("API key is working. Response:")
    print(response.json())
else:
    print(f"Failed to connect. Status Code: {response.status_code}")
    print(response.text)

API key is working. Response:
{'status': 'ok', 'message-type': 'work', 'message-version': '1.0.0', 'message': {'indexed': {'date-parts': [[2024, 12, 4]], 'date-time': '2024-12-04T12:32:55Z', 'timestamp': 1733315575422, 'version': '3.30.1'}, 'update-to': [{'updated': {'date-parts': [[2023, 7, 26]], 'date-time': '2023-07-26T00:00:00Z', 'timestamp': 1690329600000}, 'DOI': '10.1155/2022/1296993', 'type': 'retraction', 'source': 'publisher', 'label': 'Retraction'}, {'record-id': '46429', 'source': 'retraction-watch', 'label': 'Retraction', 'type': 'retraction', 'updated': {'date-time': '2023-07-26T00:00:00Z', 'date-parts': [[2023, 7, 26]], 'timestamp': 1690329600000}, 'DOI': '10.1155/2022/1296993'}], 'reference-count': 1, 'publisher': 'Wiley', 'issue': '1', 'license': [{'start': {'date-parts': [[2023, 7, 26]], 'date-time': '2023-07-26T00:00:00Z', 'timestamp': 1690329600000}, 'content-version': 'vor', 'delay-in-days': 206, 'URL': 'http://creativecommons.org/licenses/by/4.0/'}], 'content-domain': {'domain': ['onlinelibrary.wiley.com'], 'crossmark-restriction': True}, 'short-container-title': ['Computational Intelligence and Neuroscience'], 'published-print': {'date-parts': [[2023, 1]]}, 'DOI': '10.1155/2023/9834646', 'type': 'journal-article', 'created': {'date-parts': [[2023, 7, 26]], 'date-time': '2023-07-26T19:48:51Z', 'timestamp': 1690400931000}, 'update-policy': 'https://doi.org/10.1002/crossmark_policy', 'source': 'Crossref', 'is-referenced-by-count': 0, 'title': ['Retracted: Analysis of Agriculture and Food Supply Chain through Blockchain and IoT with Light Weight Cluster Head'], 'prefix': '10.1155', 'volume': '2023', 'author': [{'given': 'Computational', 'family': 'Intelligence and Neuroscience', 'sequence': 'first', 'affiliation': []}], 'member': '311', 'published-online': {'date-parts': [[2023, 7, 26]]}, 'reference': [{'key': 'e_1_2_2_1_2', 'doi-asserted-by': 'publisher', 'DOI': '10.1155/2022/1296993'}], 'container-title': ['Computational Intelligence and Neuroscience'], 'original-title': [], 'language': 'en', 'link': [{'URL': 'http://downloads.hindawi.com/journals/cin/2023/9834646.pdf', 'content-type': 'application/pdf', 'content-version': 'vor', 'intended-application': 'text-mining'}, {'URL': 'http://downloads.hindawi.com/journals/cin/2023/9834646.xml', 'content-type': 'application/xml', 'content-version': 'vor', 'intended-application': 'text-mining'}, {'URL': 'https://onlinelibrary.wiley.com/doi/pdf/10.1155/2023/9834646', 'content-type': 'unspecified', 'content-version': 'vor', 'intended-application': 'similarity-checking'}], 'deposited': {'date-parts': [[2024, 8, 6]], 'date-time': '2024-08-06T11:22:50Z', 'timestamp': 1722943370000}, 'score': 1, 'resource': {'primary': {'URL': 'https://onlinelibrary.wiley.com/doi/10.1155/2023/9834646'}}, 'subtitle': [], 'short-title': [], 'issued': {'date-parts': [[2023, 1]]}, 'references-count': 1, 'journal-issue': {'issue': '1', 'published-print': {'date-parts': [[2023, 1]]}}, 'alternative-id': ['10.1155/2023/9834646'], 'URL': 'https://doi.org/10.1155/2023/9834646', 'archive': ['Portico'], 'relation': {}, 'ISSN': ['1687-5265', '1687-5273'], 'issn-type': [{'type': 'print', 'value': '1687-5265'}, {'type': 'electronic', 'value': '1687-5273'}], 'subject': [], 'published': {'date-parts': [[2023, 1]]}, 'assertion': [{'value': '2023-07-25', 'order': 0, 'name': 'received', 'label': 'Received', 'group': {'name': 'publication_history', 'label': 'Publication History'}}, {'value': '2023-07-25', 'order': 2, 'name': 'accepted', 'label': 'Accepted', 'group': {'name': 'publication_history', 'label': 'Publication History'}}, {'value': '2023-07-26', 'order': 3, 'name': 'published', 'label': 'Published', 'group': {'name': 'publication_history', 'label': 'Publication History'}}]}}

In [18]:
import requests
import pandas as pd

API_KEY = "10a6fa24e6beeef124888369a691d5aa"
BASE_URL = "https://api.elsevier.com/content/search/scopus"

# List of DOIs
doi_csv = pd.read_csv(r"C:\Users\Parsa\OneDrive\Documents\Internship\Sadegh Suleimani Internship\Web Confrence\Files\retracted_compDataElec_DOI.csv")
dois = list(doi_csv["RetractionDOI"])  # Add all your DOIs here

headers = {
    "X-ELS-APIKey": API_KEY,
    "Accept": "application/json"
}

In [19]:
dois

['10.1155/2023/9865791',
 '10.1155/2023/9859342',
 '10.1155/2023/9849356',
 '10.1155/2023/9831958',
 '10.1155/2023/9854302',
 '10.1007/s00779-024-01841-5',
 '10.1155/2023/9782714',
 '10.1007/s00521-024-09872-y',
 '10.1155/2024/9814287',
 '10.1155/2023/9814037',
 '10.1155/2023/9801974',
 '10.1016/j.enganabound.2024.105737',
 '10.1007/s13353-024-00888-7',
 '10.1016/j.aeue.2024.155177',
 '10.1007/s12063-024-00465-5',
 '10.1007/s12063-024-00448-6',
 '10.1155/2023/9872579',
 '10.1155/2023/9826862',
 '10.1093/lambio/ovad128',
 '10.1108/HFF-12-2018-0758',
 '10.1108/hff-01-2019-0019',
 '10.1007/978-3-540-69905-7_71',
 '10.1093/llc/fqad003',
 '10.1016/j.est.2023.108957',
 '10.1155/2023/9810102',
 '10.1155/2023/9834646',
 '10.1007/s00366-023-01859-y',
 '10.1007/978-3-642-25462-8_63',
 '10.1007/978-3-642-16493-4_54',
 '10.1007/978-3-642-05253-8_80',
 '10.1007/978-3-642-02342-2_35',
 '10.1007/978-3-642-02342-2_34',
 '10.1109/ICBMI.2011.71',
 '10.1109/EPDC.2016.7514781',
 '10.1109/ECDC.2014.6836755',
 '10.1371/journal.pone.0279589',
 '10.1007/s00500-023-08595-x',
 '10.1007/978-3-540-72530-5_15',
 '10.1080/21563306.2018.11969263',
 '10.1007/s42452-023-05300-3',
 '10.1007/s40996-019-00287-7',
 '10.21595/jve.2018.20336',
 '10.1080/15567036.2015.1024986',
 '10.1080/08839514.2014.952982',
 '10.1177/09544119221147102',
 '10.1016/j.acalib.2021.102354',
 '10.1002/dac.4792',
 '10.1016/j.eswa.2011.04.025',
 '10.1038/s41598-022-16513-8',
 '10.1007/s00500-021-06289-w',
 '10.1007/s00500-021-06289-w',
 '10.1007/s12034-022-02691-8',
 '10.1016/j.eswax.2019.100013',
 '10.1007/s11277-020-08026-2',
 'Unavailable',
 '10.1016/j.commatsci.2021.111059',
 '10.1016/j.commatsci.2021.111019',
 '10.1007/s10668-021-01761-x',
 '10.1007/978-3-642-33914-1_78',
 '10.1007/978-3-642-33914-1_78',
 '10.32047/cwb.2021.26.2.3',
 '10.1007/s00521-021-06174-5',
 '10.1007/s12665-020-09030-2',
 'unavailable',
 '10.1155/2013/212769',
 '10.1007/s00521-020-05660-6',
 '10.1007/s11069-015-1602-4',
 '10.1007/s00500-021-05597-5',
 '10.1007/s00521-020-05578-z',
 '10.1007/s00521-020-05577-0',
 '10.1007/s00521-020-05575-2',
 '10.1007/s00521-020-05576-1',
 '10.1016/j.solener.2020.09.050',
 '10.1007/s10706-019-00971-5',
 '10.1007/s00521-020-05403-7',
 '10.1007/s00521-020-05271-1',
 '10.1007/s00521-020-05301-y',
 '10.1007/s00521-020-05299-3',
 '10.1007/s00521-020-05300-z',
 '10.1007/s00521-020-05122-z',
 '10.1007/s00521-020-05120-1',
 '10.1007/s00521-020-05119-8',
 '10.1007/s00521-020-05121-0',
 '10.1007/s00521-020-05153-6',
 '10.1007/s11069-020-03924-x',
 '10.1007/s00521-020-04968-7',
 '10.1007/s00521-020-04967-8',
 '10.1016/j.compag.2020.105408',
 '10.1007/s10796-016-9716-0',
 '10.1007/s10518-020-00824-0',
 '10.1007/s00521-020-04891-x',
 '10.1007/s00521-020-04892-w',
 '10.1007/s00704-020-03152-0',
 '10.1007/s00704-020-03150-2',
 'unavailable',
 '10.1007/s11852-014-0357-5',
 '10.1007/s10845-019-01493-w',
 '10.1007/s11135-019-00948-9',
 '10.1016/j.jnca.2019.102427',
 '10.1007/s40815-019-00695-x',
 '10.1093/bioinformatics/btm094',
 '10.1007/s00477-019-01673-3',
 '10.1007/s00477-019-01674-2',
 '10.1007/s00894-019-3978-7',
 '10.1007/s12230-018-9693-6',
 '10.1007/s12665-018-7997-y',
 '10.1007/s00382-015-2730-y',
 '10.1007/s00382-018-4550-3',
 '10.1007/s12053-018-9761-2',
 '10.1007/s10479-018-3103-9',
 '10.1007/s10489-018-1367-z',
 '10.1049/iet-gtd.2018.0329',
 '10.2298/FUEE1801155E',
 '10.1007/s00521-016-2691-z',
 '10.1007/s00521-012-0984-4',
 '10.1007/s00521-010-0436-y',
 '10.1007/s00521-012-0920-7',
 '10.1007/s00521-012-0983-5',
 '10.1007/s00521-012-0986-2',
 '10.1007/s00521-012-0955-9',
 '10.1007/s00521-012-0921-6',
 '10.1155/2018/4030684',
 '10.1016/j.neucom.2013.10.015',
 '10.1016/j.apenergy.2012.11.055',
 '10.1016/j.apenergy.2012.02.078',
 '10.1080/09588221.2018.1440695',
 '10.1016/j.rinp.2021.103937',
 '10.1016/j.procs.2010.12.074',
 '10.1016/j.ins.2013.07.028',
 '10.1016/j.ins.2013.07.028',
 '10.1016/j.pnucene.2013.02.004',
 '10.1016/j.infrared.2017.11.012',
 '10.1016/j.jmsy.2016.12.004',
 '10.1109/ICEMMS.2011.6015801',
 '10.1109/ICMEE.2010.5558444',
 '10.1109/APPEEC.2010.5448778',
 '10.1109/ICACC.2010.5486987',
 '10.1109/ICMEE.2010.5558448',
 '10.1109/ICEEA.2010.5596108',
 '10.1109/ICAMS.2010.5553086',
 '10.1109/ICAMS.2010.5553281',
 '10.1109/ICAMS.2010.5552982',
 '10.1109/IC4E.2010.149',
 '10.1109/IC4E.2010.56',
 '10.1109/ICCET.2010.5485554',
 '10.1109/ICSESS.2010.5552409',
 '10.1109/ICCET.2010.5486051',
 '10.1109/ICCET.2010.5486165',
 '10.1109/ICCET.2010.5486208',
 '10.1109/ICNC.2010.5584564',
 '10.1109/ICCSIT.2010.5563890',
 '10.1109/ICCSIT.2010.5565122',
 '10.1109/ICMENS.2009.46',
 '10.1007/978-3-662-47926-1_44',
 '10.4102/sajs.v108i11/12.1107',
 '10.1016/j.joei.2016.07.001',
 '10.1007/s00366-016-0441-6',
 '10.3233/IFS-162213',
 '10.1007/978-3-319-42092-9_48',
 '10.1177/1687814017710527',
 '10.1109/ICIAFS.2007.4544787',
 '10.1109/ICCTD.2009.14',
 '10.1016/j.measurement.2018.03.048',
 '10.1109/ICIMT.2009.106',
 '10.1007/978-3-319-42092-9_48',
 '10.1016/j.jvcir.2014.05.007',
 '10.1109/ICETC.2009.12',
 '10.1142/S0219622013930012',
 '10.1016/j.compbiomed.2012.06.008']

In [20]:
# Query Scopus for each DOI
results = []
for doi in dois:
    params = {"query": f"DOI({doi})"}
    response = requests.get(BASE_URL, headers=headers, params=params)
    if response.status_code == 200:
        data = response.json()
        results.append(data)
    else:
        print(f"Failed to retrieve: {doi}")

# Convert results to DataFrame
ret = pd.DataFrame(results)

In [27]:
ret.head(3)

                                      search-results
0  {'opensearch:totalResults': '2', 'opensearch:s...
1  {'opensearch:totalResults': '2', 'opensearch:s...
2  {'opensearch:totalResults': '0', 'opensearch:s...

In [34]:
# List of DOIs
doi_csv = pd.read_csv(r"C:\Users\Parsa\OneDrive\Documents\Internship\Sadegh Suleimani Internship\Web Confrence\Files\retracted_compDataElec_DOI.csv")
doi_list = list(doi_csv["RetractionDOI"])  # Add all your DOIs here

In [35]:
import requests
import pandas as pd
import time

# Scopus API Key (Replace with your actual API Key)
API_KEY = "10a6fa24e6beeef124888369a691d5aa"

# List of DOIs (Replace with your actual DOI list)
# doi_list = [
#     "10.1007/s12665-020-09030-2"
# ]

# API Endpoint
BASE_URL = "https://api.elsevier.com/content/abstract/doi/"

# Headers for API Request
HEADERS = {
    "Accept": "application/json",
    "X-ELS-APIKey": API_KEY
}

# Function to retrieve metadata for a single DOI
def get_scopus_metadata(doi):
    url = f"{BASE_URL}{doi}"
    response = requests.get(url, headers=HEADERS)

    if response.status_code == 200:
        data = response.json().get("abstracts-retrieval-response", {})

        # Extract relevant fields
        return {
            "DOI": doi,
            "Title": data.get("coredata", {}).get("dc:title", "N/A"),
            "Year": data.get("coredata", {}).get("prism:coverDate", "N/A")[:4],
            "Source title": data.get("coredata", {}).get("prism:publicationName", "N/A"),
            "Volume": data.get("coredata", {}).get("prism:volume", "N/A"),
            "Issue": data.get("coredata", {}).get("prism:issueIdentifier", "N/A"),
            "Page start": data.get("coredata", {}).get("prism:startingPage", "N/A"),
            "Page end": data.get("coredata", {}).get("prism:endingPage", "N/A"),
            "Cited by": data.get("coredata", {}).get("citedby-count", "N/A"),
            "Authors": data.get("authors", {}).get("author", "N/A"),
            "Affiliations": data.get("affiliation", "N/A"),
            "Abstract": data.get("coredata", {}).get("dc:description", "N/A"),
            "Keywords": data.get("authkeywords", "N/A"),
            "ISSN": data.get("coredata", {}).get("prism:issn", "N/A"),
            "ISBN": data.get("coredata", {}).get("prism:isbn", "N/A"),
            "Publisher": data.get("coredata", {}).get("dc:publisher", "N/A"),
            "Language": data.get("coredata", {}).get("language", "N/A"),
            "Document Type": data.get("coredata", {}).get("subtypeDescription", "N/A"),
            "Open Access": data.get("coredata", {}).get("openaccessFlag", "N/A"),
            "EID": data.get("coredata", {}).get("eid", "N/A"),
        }

    else:
        print(f"Failed to retrieve data for DOI: {doi} (Status Code: {response.status_code})")
        return {"DOI": doi, "Error": "Failed to retrieve data"}

# Iterate over DOIs and fetch metadata
metadata_list = []
for doi in doi_list:
    metadata_list.append(get_scopus_metadata(doi))
    time.sleep(10)  # Add delay to avoid API rate limits

# Convert results to DataFrame
df = pd.DataFrame(metadata_list)

# Save to CSV
df.to_csv("scopus_metadata_results.csv", index=False)

# Display results
print("Scopus metadata retrieval completed. Data saved to scopus_metadata_results.csv")

Failed to retrieve data for DOI: 10.1155/2023/9849356 (Status Code: 404)
Failed to retrieve data for DOI: 10.1155/2023/9831958 (Status Code: 404)

KeyboardInterrupt:

In [1]:
import requests
import time

# Your API key
API_KEY = "10a6fa24e6beeef124888369a691d5aa"

# List of DOIs
doi_list = [
    "10.1155/2023/9826862"
]

# Scopus API URL
BASE_URL = "https://api.elsevier.com/content/abstract/doi/"

# Headers
HEADERS = {
    "Accept": "application/json",
    "X-ELS-APIKey": API_KEY
}

# Function to fetch full metadata
def fetch_scopus_data(doi):
    url = f"{BASE_URL}{doi}?view=FULL"
    response = requests.get(url, headers=HEADERS)

    if response.status_code == 200:
        return response.json()  # Returns full metadata
    else:
        print(f"Failed for DOI {doi}, Status: {response.status_code}")
        return None

# Loop through DOIs
results = []
for doi in doi_list:
    data = fetch_scopus_data(doi)
    if data:
        results.append(data)
    time.sleep(1)  # Avoid API rate limits

print("Metadata retrieval complete!")

Failed for DOI 10.1155/2023/9826862, Status: 401
Metadata retrieval complete!

In [2]:
results

[]

In [30]:
import pandas as pd
import ast
from pandas import json_normalize

def safe_eval(x):
    # Check if x is a string; if not (or it's NaN), return an empty dict.
    if not isinstance(x, str):
        return {}
    try:
        return ast.literal_eval(x)
    except Exception as e:
        print(f"Error evaluating: {x}\nError: {e}")
        return {}

# Read the CSV file into a dataframe.
# Adjust the file name and column names as needed.
df = pd.read_csv('scopus_retracted_articles.csv', header=None, names=['row_index', 'search-result'])

# Convert the string representation of a dictionary into an actual dictionary safely.
df['response_dict'] = df['search-result'].apply(safe_eval)

# (Optional) Inspect the first few parsed responses:
print("Parsed responses:")
print(df['response_dict'].head())

# Extract the details inside the nested 'entry' key from each response.
# Since the 'entry' value is a list (which may contain one or more entries), you can flatten these out.
entries = []  # List to collect each individual entry along with its source row

for idx, resp in df['response_dict'].iteritems():
    # The API response may include an 'entry' key.
    # For example, a response might be:
    # {'opensearch:totalResults': '2', ... , 'entry': [ { ... }, { ... } ]}
    if 'entry' in resp:
        for entry in resp['entry']:
            # Optionally, add a column to keep track of which row this entry came from.
            entry['source_row'] = idx
            entries.append(entry)
    else:
        # Handle responses without an 'entry' key.
        print(f"No 'entry' in response at row {idx}")

# Now normalize the list of entries into a flat dataframe.
if entries:
    entries_df = json_normalize(entries)
    print("\nExtracted entries:")
    print(entries_df.head())
else:
    print("No entries found in any response.")

# You can now work with 'entries_df' as needed.

Parsed responses:
0    {}
1    {}
2    {}
3    {}
4    {}
Name: response_dict, dtype: object

AttributeError: 'Series' object has no attribute 'iteritems'

In [10]:
# Save to Excel or CSV
ret.to_csv("scopus_retracted_articles.csv", index=False)

In [4]:
# Searching for specific terms
search_terms = ['computer science', 'data science', 'engineering -electrical']
results = iran_articles[iran_articles['Subject'].str.contains('|'.join(search_terms), case=False, na=False)]

In [5]:
results

,Record ID,Title,Subject,Institution,Journal,Publisher,Country,Author,URLS,ArticleType,RetractionDate,RetractionDOI,RetractionPubMedID,OriginalPaperDate,OriginalPaperDOI,OriginalPaperPubMedID,RetractionNature,Reason,Paywalled,Notes
230,60949,An Architectural Framework for Healthcare Dash...,(B/T) Data Science;(B/T) Technology;(HSC) Medi...,"Faculty of Management, University of Tehran, T...",Journal of Healthcare Engineering,Hindawi,Iran,Saeed Rouhani;Shooka Zamenian,https://retractionwatch.com/2022/09/28/exclusi...,Review Article;,11/1/2023 0:00,10.1155/2023/9865791,37946909.0,10/27/2021 0:00,10.1155/2021/1964054,34745492.0,Retraction,+Concerns/Issues About Data;+Concerns/Issues A...,No,NaN
646,60474,Clustering of Brain Tumor Based on Analysis of...,(B/T) Computer Science;(B/T) Technology;(HSC) ...,"Department of Industrial Engineering, Islamic ...",BioMed Research International,Hindawi,Iran,Ali Hamzenejad;Saeid Jafarzadeh Ghoushchi;Vahi...,https://retractionwatch.com/2022/09/28/exclusi...,Research Article;,11/29/2023 0:00,10.1155/2023/9859342,38075360.0,8/31/2021 0:00,10.1155/2021/5516819,34504897.0,Retraction,+Fake Peer Review;+Investigation by Journal/Pu...,No,NaN
871,60249,Using a Blur Metric to Estimate Linear Motion ...,(B/T) Computer Science;(HSC) Radiology/Imaging;,"Computer Science Department, Faculty of Mathem...",Computational and Mathematical Methods in Medi...,Hindawi,Iran,Taiebeh Askari Javaran;Hamid Hassanpour,https://retractionwatch.com/2022/09/28/exclusi...,Research Article;,12/6/2023 0:00,10.1155/2023/9849356,38094468.0,10/28/2021 0:00,10.1155/2021/6048137,34745327.0,Retraction,+Fake Peer Review;+Investigation by Journal/Pu...,No,NaN
1076,60044,Method of Cumulative Anomaly Identification fo...,(B/T) Computer Science;(B/T) Technology;,"Shaoxing University Yuanpei College, Shaoxing ...",Security and Communication Networks,Hindawi,China;Iran,Zhiying Xu;Ting Yang;Moslem Lari Najafi,https://retractionwatch.com/2022/09/28/exclusi...,Research Article;,12/6/2023 0:00,10.1155/2023/9831958,0.0,3/21/2022 0:00,10.1155/2022/5113725,0.0,Retraction,+Fake Peer Review;+Investigation by Journal/Pu...,No,NaN
1404,59716,A Computer-Aided Method for Digestive System A...,(B/T) Data Science;(B/T) Technology;(HSC) Medi...,"Image Processing and Data Mining Lab, Shahrood...",Journal of Healthcare Engineering,Hindawi,France;Iran,Zahra Amiri;Hamid Hassanpour;Azeddine Beghdadi,https://retractionwatch.com/2022/09/28/exclusi...,Research Article;,12/6/2023 0:00,10.1155/2023/9854302,38094789.0,10/18/2021 0:00,10.1155/2021/7863113,34707798.0,Retraction,+Fake Peer Review;+Investigation by Journal/Pu...,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53850,7034,A Novel Voting Mathematical Rule Classificatio...,(B/T) Computer Science;(PHY) Mathematics;,"Department of Computer Engineering, Iran Healt...",Lecture Notes in Computer Science,Springer,Iran,Sadrollah Abbasi;Afshin Shahriari;Yaser Nemati,NaN,Book Chapter/Reference Work;,12/27/2016 0:00,10.1007/978-3-319-42092-9_48,NaN,7/1/2016 0:00,10.1007/978-3-319-42092-9_20,NaN,Retraction,+Plagiarism of Article;,No,International Conference on Computational Scie...
53853,7031,Pose invariant face recognition using biologic...,(B/T) Computer Science;(B/T) Data Science;,"Faculty of Electrical Engineering, Iran Univer...",Journal of Visual Communication and Image Repr...,Elsevier,Iran,Masoud Ghaderi Dehkordi;Mohammad Reza Daliri;A...,http://retractionwatch.com/2015/06/22/plagiari...,Research Article;,5/26/2014 0:00,10.1016/j.jvcir.2014.05.007,0.0,6/18/2013 0:00,10.1016/j.jvcir.2013.06.007,0.0,Retraction,+Breach of Policy by Author;+Plagiarism of Art...,No,NaN
53953,6929,Fuzzy PID Sliding Mode Controller Design for t...,(B/T) Computer Science;(B/T) Technology;(PHY) ...,"Department of Mechatronics Engineering, Semnan...",2009 International Conference on Education Tec...,IEEE: Institute of Electrical and Electronics ...,Iran,Mohsen Fallahi;Sassan Azadi,https://retractionwatch.com/2015/06/25/one-pub...,Conference Abstract/Paper;,7/21/2009 0:00,10.1109/ICETC.2009.12,0.0,4/17/2009 0:00,10.1109/ICETC.2009.12,0.0,Retraction,+Breach of Policy by Author;+Date of Retractio...,No,"Date of retraction unknown, estimated from con..."
55250,5610,A Lagrangian-based Solution Algorithm for Stra...,(B/T) Business - Marketing;(B/T) Computer Scie...,"Department of Industrial Engineering, Amirkabi...",International Journal of Information Technolog...,World Scientific Publishing Company,Iran,G Reza Nasiri;Hamid Davoudpour;Behrooz Karimi,NaN,Research Article;,1/1/2013 0:00,10.1142/S0219622013930012,0.0,5/1/2010 0:00,10.1142/S0219622010003877,0.0,Retraction,+Duplication of Article;,Yes,NaN
56237,4600,A novel real-time patient-specific seizure dia...,(B/T) Computer Science;(HSC) Radiology/Imaging;,"Department of Electrical Engineering, Najafaba...",Computers in Biology and Medicine,Elsevier,Iran,Saadat Nasehi;Hossein Pourghassem,http://retractionwatch.com/2013/01/17/note-to-...,Research Article;,3/1/2013 0:00,10.1016/j.compbiomed.2012.06.008,23520624.0,7/15/2012 0:00,NaN,22795227.0,Retraction,+Concerns/Issues About Results;+Plagiarism of ...,No,NaN

In [11]:
results[results["Subject"].str.contains('engineering - electrical', case=False, na=False)]

,Record ID,Title,Subject,Institution,Journal,Publisher,Country,Author,URLS,ArticleType,RetractionDate,RetractionDOI,RetractionPubMedID,OriginalPaperDate,OriginalPaperDOI,OriginalPaperPubMedID,RetractionNature,Reason,Paywalled,Notes
7884,53211,Minimizing cosecant-squared pattern side lobe ...,(B/T) Computer Science;(B/T) Data Science;(PHY...,"Electrical and Computer Engineering Faculty, S...",AEU - International Journal of Electronics and...,Elsevier,Iran,Mehdi Sharifi;Pejman Rezaei,NaN,Research Article;,2/15/2024 0:00,10.1016/j.aeue.2024.155177,0.0,12/25/2021 0:00,10.1016/j.aeue.2021.154076,0.0,Retraction,+Euphemisms for Plagiarism;+Plagiarism of Arti...,No,NaN
12492,48590,A Novel Text-Independent Speaker Verification ...,(B/T) Data Science;(B/T) Technology;(PHY) Engi...,Department of Electrical and Computer Engineer...,ICISP 2008: Image and Signal Processing,Springer,Iran,Shahla Nemati;Reza Boostani;Mohammad Davarpana...,NaN,Conference Abstract/Paper;,7/20/2023 0:00,10.1007/978-3-540-69905-7_71,0.0,7/1/2008 0:00,10.1007/978-3-540-69905-7_48,0.0,Retraction,+Date of Retraction/Other Unknown;+Plagiarism ...,No,"date of retraciton unknown, date estimated fro..."
14057,47022,Energy management of wind-PV-storage-grid base...,(B/T) Computer Science;(PHY) Energy;(PHY) Engi...,Key Laboratory of Modern Power System Simulati...,Journal of Energy Storage,Elsevier,China;Iran;Thailand,Dongmin Yu;Tao Zhang;Guixiong He;Sayyad Nojava...,NaN,Research Article;,9/14/2023 0:00,10.1016/j.est.2023.108957,0.0,11/11/2019 0:00,10.1016/j.est.2019.101054,0.0,Retraction,+Breach of Policy by Author;+Concerns/Issues A...,No,NaN
15436,45635,Chaotic simulation of the multi-phase reinforc...,(B/T) Computer Science;(PHY) Engineering - Ele...,"School of Mechanical Engineering, Hangzhou Dia...",Engineering with Computers,Springer,Algeria;China;Iran;Vietnam,M S H Al-Furjan;Mostafa Habibi;Alireza Rahimi;...,https://retractionwatch.com/2023/05/12/paper-w...,Research Article;,6/9/2023 0:00,10.1007/s00366-023-01859-y,0.0,8/25/2020 0:00,10.1007/s00366-020-01144-2,0.0,Retraction,+Concerns/Issues with Peer Review;+Duplication...,No,NaN
15887,45184,Pareto optimal reconfiguration of power distri...,(B/T) Computer Science;(PHY) Energy;(PHY) Engi...,"Department of Electrical Engineering, Lorestan...",2016 21st Conference on Electrical Power Distr...,IEEE: Institute of Electrical and Electronics ...,Iran,Sina Khajeh Ahmad Attari;Mahmoud Reza Shakaram...,NaN,Conference Abstract/Paper;,7/18/2016 0:00,10.1109/EPDC.2016.7514781,0.0,4/26/2016 0:00,10.1109/EPDC.2016.7514781,0.0,Retraction,+Concerns/Issues about Referencing/Attribution...,No,NaN
15893,45178,e-STAB: Energy-efficient scheduling for cloud ...,(B/T) Computer Science;(B/T) Technology;(PHY) ...,"Msc student of software engineering, ghazvin a...",8th International Conference on e-Commerce in ...,IEEE: Institute of Electrical and Electronics ...,Iran,Fatemeh Heydarikiya;Abolfazl Toroghy Haghighat...,NaN,Conference Abstract/Paper;,6/19/2014 0:00,10.1109/ECDC.2014.6836755,0.0,4/24/2014 0:00,10.1109/ECDC.2014.6836755,0.0,Retraction,+Concerns/Issues about Referencing/Attribution...,No,NaN
26026,34986,Improved AODV Based on TOPSIS and Fuzzy Algori...,(B/T) Computer Science;(B/T) Technology;(PHY) ...,Department of Electrical and Computer Engineer...,Wireless Personal Communications,Springer,Iran,Esmaeil Amiri;Reza Hooshmand,NaN,Research Article;,12/22/2020 0:00,10.1007/s11277-020-08026-2,0.0,11/7/2019 0:00,10.1007/s11277-019-06894-x,0.0,Retraction,+Euphemisms for Plagiarism;+Plagiarism of Arti...,No,NaN
36573,24410,Information gap decision theory-based risk-con...,(B/T) Computer Science;(B/T) Technology;(PHY) ...,Faculty of Electrical and Computer Engineering...,Solar Energy,Elsevier,Iran,Afshin Najafi-Ghalelou;Sayyad Nojavan;Kazem Zare,NaN,Research Article;,9/29/2020 0:00,10.1016/j.solener.2020.09.050,0.0,2/9/2018 0:00,10.1016/j.solener.2018.02.013,0.0,Retraction,+Duplication of Article;,No,NaN
40436,20533,Support vector regression methodology for pred...,(B/T) Computer Science;(ENV) Environmental Sci...,Department of Agricultural Machinery Engineeri...,Stochastic Environmental Research and Risk Ass...,Springer,Iran;Malaysia,Marziye Yousefi;Benyamin Khishnevisan;Shahabod...,NaN,Research Article;,5/29/2019 0:00,10.1007/s00477-019-01674-2,0.0,3/21/2015 0:00,10.1007/s00477-015-1055-z,0.0,Retraction,+Concerns/Issues About Authorship/Affiliation;...,No,NaN
41324,19638,Soft computing methodologies for estimation of...,(B/T) Computer Science;(PHY) Energy;(PHY) Engi...,"Department of Civil Engineering, Faculty of En...",Energy Efficiency,Springer,Iran;Malaysia,Sareh Naji;Shahaboddin Shamshirband;Hamed Bass...,http://retractionwatch.com/?s=Shahaboddin+Sham...,Research Article;,12/7/2018 0:00,10.1007/s12053-018-9761-2,0.0,7/10/2015 0:00,10.1007/s12053-015-9373-z,0.0,Retraction,+Complaints about Author;+Concerns/Issues Abou...,No,NaN
42744,18211,Temperature control of a cabin in an automobil...,(B/T) Computer Science;(B/T) Transportation;(P...,"Energy Systems Improvement Laboratory (ESIL), ...",Applied Energy,Elsevier,Canada;Iran,Sepehr Sanaye;Masoud Dehghandokht;Amir Fartaj,NaN,Research Article;,12/20/2012 0:00,10.1016/j.apenergy.2012.11.055,0.0,4/26/2012 0:00,10.1016/j.apenergy.2012.02.078,0.0,Correction,+Concerns/Issues About Authorship/Affiliation;,No,Correction adds Navid Kashaninejad to author l...
42745,18210,Temperature control of a cabin in an automobil...,(B/T) Computer Science;(B/T) Transportation;(P...,"Energy Systems Improvement Laboratory (ESIL), ...",Applied Energy,Elsevier,Canada;Iran,Sepehr Sanaye;Masoud Dehghandokht;Amir Fartaj,NaN,Research Article;,3/1/2013 0:00,10.1016/j.apenergy.2012.02.078,0.0,4/26/2012 0:00,10.1016/j.apenergy.2012.02.078,0.0,Retraction,+Objections by Third Party;+Plagiarism of Arti...,No,exact date of retraction unknown;
45913,15016,Optimal placement and sizing of DG and capacit...,(B/T) Computer Science;(PHY) Engineering - Ele...,"Department of Electrical Engineering, Centre o...",2010 Asia-Pacific Power and Energy Engineering...,IEEE: Institute of Electrical and Electronics ...,Iran,Kazem Haghdar;Heidar Ali Shayanfar,http://retractionwatch.com/2015/06/25/one-publ...,Conference Abstract/Paper;,4/15/2010 0:00,10.1109/APPEEC.2010.5448778,0.0,3/28/2010 0:00,10.1109/APPEEC.2010.5448778,0.0,Retraction,+Breach of Policy by Author;+Date of Retractio...,No,"Date of retraction unknown, estimated from con..."
52798,8099,Kinetostatic Analysis of Passively Adaptive Ro...,(B/T) Computer Science;(B/T) Technology;(PHY) ...,"University of Niš, Faculty of Mechanical Engin...",Advances in Mechanical Engineering,SAGE Publications,Iran;Malaysia;Serbia,Dalibor Petkovic;Javed Iqbal;Shahaboddin Shams...,http://retractionwatch.com/?s=Shahaboddin+Sham...,Research Article;,5/22/2017 0:00,10.1177/1687814017710527,0.0,2/12/2015 0:00,10.1155/2014/145648,0.0,Retraction,+Duplication of Article;+Euphemisms for Duplic...,No,NaN

In [ ]:
import pandas as pd

# Load the dataset
file_path = 'scopus_retracted_articles.csv'
df = pd.read_csv(file_path)

# Define the columns to extract and rename them for clarity
tidy_data = df.rename(columns={
    'dc:title': 'Title',
    'prism:publicationName': 'Publication Name',
    'prism:volume': 'Volume',
    'prism:doi': 'DOI',
    'prism:coverDate': 'Cover Date',
    'citedby-count': 'Cited By Count',
    'prism:aggregationType': 'Aggregation Type',
    'subtypeDescription': 'Subtype Description'
})

# Keep only the relevant columns
columns_to_keep = [
    'Title',
    'Publication Name',
    'Volume',
    'DOI',
    'Cover Date',
    'Cited By Count',
    'Aggregation Type',
    'Subtype Description'
]
tidy_data = tidy_data[columns_to_keep]

# Save the tidied data to a new CSV file
output_file = 'tidy_scopus_retracted_articles.csv'
tidy_data.to_csv(output_file, index=False)

print(f"Tidied data saved to {output_file}")

In [5]:
import csv
import json

def flatten_json(data, parent_key='', sep='.'):
    """
    Recursively flattens a nested dictionary or list.

    Parameters:
        data (dict or list): The JSON structure to flatten.
        parent_key (str): The prefix for keys (used during recursion).
        sep (str): Separator between keys.

    Returns:
        dict: A flattened dictionary where nested keys are concatenated.
    """
    items = {}
    if isinstance(data, dict):
        for key, value in data.items():
            new_key = f"{parent_key}{sep}{key}" if parent_key else key
            items.update(flatten_json(value, new_key, sep=sep))
    elif isinstance(data, list):
        for i, value in enumerate(data):
            new_key = f"{parent_key}{sep}{i}" if parent_key else str(i)
            items.update(flatten_json(value, new_key, sep=sep))
    else:
        items[parent_key] = data
    return items

def process_csv(input_file, output_file):
    """
    Processes an input CSV file cell-by-cell:
        - If a cell contains valid JSON (and that JSON is a dict or list),
          it flattens the JSON and prefixes the flattened keys with the original column name.
        - Otherwise, the cell's content is preserved.
    The function then writes all rows into a new CSV file with appropriate column headers.

    Parameters:
        input_file (str): Path to the input CSV file.
        output_file (str): Path to the output CSV file.
    """
    processed_rows = []    # List of dictionaries (one per row) after processing
    all_columns = set()    # To collect all column headers that will appear in the output

    # Open and read the input CSV file (assumed to have headers)
    with open(input_file, 'r', encoding='utf-8', newline='') as csv_in:
        reader = csv.DictReader(csv_in)
        for row in reader:
            new_row = {}
            # Process each cell in the row
            for col, cell in row.items():
                # If cell is nonempty, try to parse it as JSON
                if cell.strip():
                    try:
                        parsed = json.loads(cell)
                        # If the cell is valid JSON and it is a dict or list,
                        # flatten it.
                        if isinstance(parsed, (dict, list)):
                            flat = flatten_json(parsed)
                            # For each flattened key, prefix with the original column name.
                            for k, v in flat.items():
                                # For clarity, if k is empty, simply use the column name.
                                new_col = f"{col}{'.' if k else ''}{k}" if k else col
                                new_row[new_col] = v
                                all_columns.add(new_col)
                        else:
                            # For JSON values that are simple (e.g., numbers, strings), keep as is.
                            new_row[col] = parsed
                            all_columns.add(col)
                    except json.JSONDecodeError:
                        # If the cell is not valid JSON, simply keep the original value.
                        new_row[col] = cell
                        all_columns.add(col)
                else:
                    # If the cell is empty, simply pass it along.
                    new_row[col] = cell
                    all_columns.add(col)
            processed_rows.append(new_row)

    # Sort the column headers (this helps keep the output consistent)
    fieldnames = sorted(all_columns)

    # Write the flattened data to the output CSV file.
    with open(output_file, 'w', encoding='utf-8', newline='') as csv_out:
        writer = csv.DictWriter(csv_out, fieldnames=fieldnames)
        writer.writeheader()
        for row in processed_rows:
            writer.writerow(row)

if __name__ == '__main__':
    # Define your input and output CSV file names here.
    input_csv = 'scopus_retracted_articles.csv'
    output_csv = 'output.csv'

    process_csv(input_csv, output_csv)
    print(f"Processed CSV written to {output_csv}")

Processed CSV written to output.csv

In [7]:
import csv
import ast
import re

def flatten_json(nested_json, parent_key='', sep='.'):
    """
    Recursively flattens a nested JSON/dictionary.
    For lists, it uses the index as a key.
    """
    items = {}
    if isinstance(nested_json, dict):
        for k, v in nested_json.items():
            new_key = f"{parent_key}{sep}{k}" if parent_key else k
            items.update(flatten_json(v, new_key, sep=sep))
    elif isinstance(nested_json, list):
        for i, v in enumerate(nested_json):
            new_key = f"{parent_key}{sep}{i}" if parent_key else str(i)
            items.update(flatten_json(v, new_key, sep=sep))
    else:
        items[parent_key] = nested_json
    return items

def extract_link(link_list, ref="scopus"):
    """
    Given a list of link dictionaries, returns the @href value for the one whose @ref equals 'scopus'
    (or another value if specified).
    """
    if isinstance(link_list, list):
        for item in link_list:
            if isinstance(item, dict) and item.get('@ref') == ref:
                return item.get('@href', '')
    return ''

def process_entry(entry):
    """
    Processes a single paper record (an entry from the input data) by flattening it and extracting
    selected fields into a dictionary whose keys match the desired output columns.
    """
    # Flatten the entry
    flat = flatten_json(entry)

    out = {}
    # --- mapping keys to desired output columns ---
    out["Title"] = flat.get("dc:title", "")

    # Extract year from cover date (assumed format "YYYY-MM-DD")
    cover_date = flat.get("prism:coverDate", "")
    if cover_date:
        m = re.match(r"(\d{4})", cover_date)
        out["Year"] = m.group(1) if m else ""
    else:
        out["Year"] = ""

    out["Source title"] = flat.get("prism:publicationName", "")
    out["Volume"] = flat.get("prism:volume", "")
    out["Issue"] = flat.get("issue", "") or flat.get("prism:issueIdentifier", "")
    out["Art. No."] = flat.get("article-number", "")

    # Process page range
    page_range = flat.get("prism:pageRange", "")
    if page_range:
        if '-' in page_range:
            parts = page_range.split('-')
            out["Page start"] = parts[0].strip()
            out["Page end"] = parts[1].strip() if len(parts) > 1 else ""
            try:
                start = int(parts[0].strip())
                end = int(parts[1].strip())
                out["Page count"] = str(end - start + 1)
            except Exception:
                out["Page count"] = ""
        else:
            out["Page start"] = page_range
            out["Page end"] = ""
            out["Page count"] = ""
    else:
        out["Page start"] = ""
        out["Page end"] = ""
        out["Page count"] = ""

    out["Cited by"] = flat.get("citedby-count", "")
    out["DOI"] = flat.get("prism:doi", "")

    # Extract link (using the original entry if available)
    if "link" in entry:
        out["Link"] = extract_link(entry["link"], ref="scopus")
    else:
        out["Link"] = ""

    # Process affiliations
    if "affiliation" in entry:
        aff = entry["affiliation"]
        if isinstance(aff, list):
            aff_list = []
            for a in aff:
                if isinstance(a, dict):
                    parts = []
                    for key in ["affilname", "affiliation-city", "affiliation-country"]:
                        if key in a:
                            parts.append(a[key])
                    aff_list.append(", ".join(parts))
                else:
                    aff_list.append(str(a))
            out["Affiliations"] = "; ".join(aff_list)
        else:
            out["Affiliations"] = str(aff)
    else:
        out["Affiliations"] = ""

    out["PubMed ID"] = flat.get("pubmed-id", "")
    out["EID"] = flat.get("eid", "")
    out["Authors"] = flat.get("dc:creator", "")

    # For fields not available from the input, output empty strings.
    extra_fields = [
        "Author full names", "Author(s) ID", "Authors with affiliations", "Abstract",
        "Author Keywords", "Index Keywords", "Molecular Sequence Numbers", "Chemicals/CAS",
        "Tradenames", "Manufacturers", "Funding Details", "Funding Texts", "References",
        "Correspondence Address", "Editors", "Publisher", "Sponsors", "Conference name",
        "Conference date", "Conference location", "Conference code", "ISSN", "ISBN",
        "CODEN", "Language of Original Document", "Abbreviated Source Title",
        "Document Type", "Publication Stage", "Open Access", "Source"
    ]
    for field in extra_fields:
        out[field] = ""

    return out

def process_csv(input_file, output_file):
    """
    Reads an input CSV file where each row contains a Python dictionary literal (as a string),
    processes each record, and writes an output CSV file with the desired columns.
    """
    headers = [
        "Authors", "Author full names", "Author(s) ID", "Title", "Year",
        "Source title", "Volume", "Issue", "Art. No.", "Page start", "Page end",
        "Page count", "Cited by", "DOI", "Link", "Affiliations",
        "Authors with affiliations", "Abstract", "Author Keywords", "Index Keywords",
        "Molecular Sequence Numbers", "Chemicals/CAS", "Tradenames", "Manufacturers",
        "Funding Details", "Funding Texts", "References", "Correspondence Address",
        "Editors", "Publisher", "Sponsors", "Conference name", "Conference date",
        "Conference location", "Conference code", "ISSN", "ISBN", "CODEN",
        "PubMed ID", "Language of Original Document", "Abbreviated Source Title",
        "Document Type", "Publication Stage", "Open Access", "Source", "EID"
    ]

    output_rows = []

    with open(input_file, 'r', encoding='utf-8') as fin:
        reader = csv.reader(fin)
        for row in reader:
            if not row:
                continue
            cell = row[0].strip()
            # Skip header or invalid rows that don't start with a brace
            if not cell.startswith('{'):
                continue
            try:
                # Use ast.literal_eval to parse Python literal dictionaries
                data = ast.literal_eval(cell)
            except Exception as e:
                print("Error decoding data with ast.literal_eval:", e)
                continue

            # If the data contains an "entry" key that is a list, process each paper record.
            if "entry" in data and isinstance(data["entry"], list):
                for entry in data["entry"]:
                    out_row = process_entry(entry)
                    output_rows.append(out_row)

    with open(output_file, 'w', newline='', encoding='utf-8') as fout:
        # Using tab as the delimiter (change to ',' if desired)
        writer = csv.DictWriter(fout, fieldnames=headers, delimiter='\t')
        writer.writeheader()
        for row in output_rows:
            writer.writerow(row)

if __name__ == '__main__':
    input_csv = 'scopus_retracted_articles.csv'
    output_csv = 'output3.csv'

    process_csv(input_csv, output_csv)
    print("Processing complete. Output saved to", output_csv)

Processing complete. Output saved to output3.csv

In [8]:
import ast
import re
import pprint

def flatten_json(nested_json, parent_key='', sep='.'):
    """
    Recursively flatten a nested dictionary (or list) into a single-level dict.
    List indices become keys as well.
    """
    items = {}
    if isinstance(nested_json, dict):
        for k, v in nested_json.items():
            new_key = f"{parent_key}{sep}{k}" if parent_key else k
            items.update(flatten_json(v, new_key, sep=sep))
    elif isinstance(nested_json, list):
        for i, v in enumerate(nested_json):
            new_key = f"{parent_key}{sep}{i}" if parent_key else str(i)
            items.update(flatten_json(v, new_key, sep=sep))
    else:
        items[parent_key] = nested_json
    return items

def process_entry(entry):
    """
    Process one paper record (one entry from the API response) and extract selected fields.
    The function uses flatten_json to make nested keys accessible and then maps them to our
    desired output.
    """
    flat = flatten_json(entry)
    out = {}

    # Title
    out["Title"] = flat.get("dc:title", "")

    # Year: extract the four-digit year from prism:coverDate (expected format "YYYY-MM-DD")
    cover_date = flat.get("prism:coverDate", "")
    if cover_date:
        m = re.match(r"(\d{4})", cover_date)
        out["Year"] = m.group(1) if m else ""
    else:
        out["Year"] = ""

    # Source title, Volume, and Issue
    out["Source title"] = flat.get("prism:publicationName", "")
    out["Volume"] = flat.get("prism:volume", "")
    out["Issue"] = flat.get("prism:issueIdentifier", "")

    # Article number
    out["Art. No."] = flat.get("article-number", "")

    # Process page range (if available)
    page_range = flat.get("prism:pageRange", "")
    if page_range and isinstance(page_range, str):
        if '-' in page_range:
            parts = page_range.split('-')
            out["Page start"] = parts[0].strip()
            out["Page end"] = parts[1].strip() if len(parts) > 1 else ""
            try:
                start = int(parts[0].strip())
                end = int(parts[1].strip())
                out["Page count"] = str(end - start + 1)
            except Exception:
                out["Page count"] = ""
        else:
            out["Page start"] = page_range
            out["Page end"] = ""
            out["Page count"] = ""
    else:
        out["Page start"] = ""
        out["Page end"] = ""
        out["Page count"] = ""

    # Other fields
    out["Cited by"] = flat.get("citedby-count", "")
    out["DOI"] = flat.get("prism:doi", "")
    out["PubMed ID"] = flat.get("pubmed-id", "")
    out["EID"] = flat.get("eid", "")

    return out

# --- Main code: process a single API response ---

# This is our API response provided as a Python dictionary literal (using single quotes)
api_response_str = """{'opensearch:totalResults': '2', 'opensearch:startIndex': '0', 'opensearch:itemsPerPage': '2', 'opensearch:Query': {'@role': 'request', '@searchTerms': 'DOI(10.1093/lambio/ovad128)', '@startPage': '0'}, 'link': [{'@_fa': 'true', '@ref': 'self', '@href': 'https://api.elsevier.com/content/search/scopus?start=0&count=25&query=DOI%2810.1093%2Flambio%2Fovad128%29', '@type': 'application/json'}, {'@_fa': 'true', '@ref': 'first', '@href': 'https://api.elsevier.com/content/search/scopus?start=0&count=25&query=DOI%2810.1093%2Flambio%2Fovad128%29', '@type': 'application/json'}], 'entry': [{'@_fa': 'true', 'link': [{'@_fa': 'true', '@ref': 'self', '@href': 'https://api.elsevier.com/content/abstract/scopus_id/85192007415'}, {'@_fa': 'true', '@ref': 'author-affiliation', '@href': 'https://api.elsevier.com/content/abstract/scopus_id/85192007415?field=author,affiliation'}, {'@_fa': 'true', '@ref': 'scopus', '@href': 'https://www.scopus.com/inward/record.uri?partnerID=HzOxMe3b&scp=85192007415&origin=inward'}, {'@_fa': 'true', '@ref': 'scopus-citedby', '@href': 'https://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&scp=85192007415&origin=inward'}], 'prism:url': 'https://api.elsevier.com/content/abstract/scopus_id/85192007415', 'dc:identifier': 'SCOPUS_ID:85192007415', 'eid': '2-s2.0-85192007415', 'dc:title': 'Retraction: wbeT sequence typing and IS1004 profiling of Vibrio cholerae isolates (Letters in Applied Microbiology (2012) 54: 4 (267-271) DOI: 10.1111/j.1472-765X.2012.03204.x)', 'prism:publicationName': 'Letters in Applied Microbiology', 'prism:issn': '02668254', 'prism:eIssn': '1472765X', 'prism:volume': '76', 'prism:issueIdentifier': '11', 'prism:pageRange': None, 'prism:coverDate': '2023-11-01', 'prism:coverDisplayDate': 'November 2023', 'prism:doi': '10.1093/lambio/ovad128', 'citedby-count': '0', 'pubmed-id': '37981405', 'prism:aggregationType': 'Journal', 'subtype': 'er', 'subtypeDescription': 'Erratum', 'article-number': 'ovad128', 'source-id': '20254', 'openaccess': '1', 'openaccessFlag': True, 'freetoread': {'value': [{'$': 'all'}, {'$': 'publisherhybridgold'}]}, 'freetoreadLabel': {'value': [{'$': 'All Open Access'}, {'$': 'Hybrid Gold'}]}}, {'@_fa': 'true', 'link': [{'@_fa': 'true', '@ref': 'self', '@href': 'https://api.elsevier.com/content/abstract/scopus_id/85177437136'}, {'@_fa': 'true', '@ref': 'author-affiliation', '@href': 'https://api.elsevier.com/content/abstract/scopus_id/85177437136?field=author,affiliation'}, {'@_fa': 'true', '@ref': 'scopus', '@href': 'https://www.scopus.com/inward/record.uri?partnerID=HzOxMe3b&scp=85177437136&origin=inward'}, {'@_fa': 'true', '@ref': 'scopus-citedby', '@href': 'https://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&scp=85177437136&origin=inward'}], 'prism:url': 'https://api.elsevier.com/content/abstract/scopus_id/85177437136', 'dc:identifier': 'SCOPUS_ID:85177437136', 'eid': '2-s2.0-85177437136', 'dc:title': 'Retraction of: wbeT sequence typing and IS1004 profiling of Vibrio cholerae isolates', 'prism:publicationName': 'Letters in applied microbiology', 'prism:eIssn': '1472765X', 'prism:volume': '76', 'prism:issueIdentifier': '11', 'prism:pageRange': None, 'prism:coverDate': '2023-11-01', 'prism:coverDisplayDate': '1 November 2023', 'prism:doi': '10.1093/lambio/ovad128', 'citedby-count': '0', 'pubmed-id': '37981405', 'prism:aggregationType': 'Journal', 'subtype': 'er', 'subtypeDescription': 'Erratum', 'source-id': '20254', 'openaccess': '1', 'openaccessFlag': True, 'freetoread': {'value': [{'$': 'all'}, {'$': 'publisherhybridgold'}]}, 'freetoreadLabel': {'value': [{'$': 'All Open Access'}, {'$': 'Hybrid Gold'}]}}]}"""

# Convert the string to a Python dictionary
api_response = ast.literal_eval(api_response_str)

# Extract the list of entries (i.e. paper records)
entries = api_response.get("entry", [])

# Process each entry and print the results
for i, entry in enumerate(entries, start=1):
    processed = process_entry(entry)
    print(f"--- Entry {i} ---")
    pprint.pprint(processed)

--- Entry 1 ---
{'Art. No.': 'ovad128',
 'Cited by': '0',
 'DOI': '10.1093/lambio/ovad128',
 'EID': '2-s2.0-85192007415',
 'Issue': '11',
 'Page count': '',
 'Page end': '',
 'Page start': '',
 'PubMed ID': '37981405',
 'Source title': 'Letters in Applied Microbiology',
 'Title': 'Retraction: wbeT sequence typing and IS1004 profiling of Vibrio '
          'cholerae isolates (Letters in Applied Microbiology (2012) 54: 4 '
          '(267-271) DOI: 10.1111/j.1472-765X.2012.03204.x)',
 'Volume': '76',
 'Year': '2023'}
--- Entry 2 ---
{'Art. No.': '',
 'Cited by': '0',
 'DOI': '10.1093/lambio/ovad128',
 'EID': '2-s2.0-85177437136',
 'Issue': '11',
 'Page count': '',
 'Page end': '',
 'Page start': '',
 'PubMed ID': '37981405',
 'Source title': 'Letters in applied microbiology',
 'Title': 'Retraction of: wbeT sequence typing and IS1004 profiling of Vibrio '
          'cholerae isolates',
 'Volume': '76',
 'Year': '2023'}

In [12]:
doi_csv = pd.read_csv(r"C:\Users\Parsa\OneDrive\Documents\Internship\Sadegh Suleimani Internship\Web Confrence\Files\retracted_compDataElec_DOI.csv")
doi_list = list(doi_csv["RetractionDOI"])

In [13]:
doi_list

['10.1155/2023/9865791',
 '10.1155/2023/9859342',
 '10.1155/2023/9849356',
 '10.1155/2023/9831958',
 '10.1155/2023/9854302',
 '10.1007/s00779-024-01841-5',
 '10.1155/2023/9782714',
 '10.1007/s00521-024-09872-y',
 '10.1155/2024/9814287',
 '10.1155/2023/9814037',
 '10.1155/2023/9801974',
 '10.1016/j.enganabound.2024.105737',
 '10.1007/s13353-024-00888-7',
 '10.1016/j.aeue.2024.155177',
 '10.1007/s12063-024-00465-5',
 '10.1007/s12063-024-00448-6',
 '10.1155/2023/9872579',
 '10.1155/2023/9826862',
 '10.1093/lambio/ovad128',
 '10.1108/HFF-12-2018-0758',
 '10.1108/hff-01-2019-0019',
 '10.1007/978-3-540-69905-7_71',
 '10.1093/llc/fqad003',
 '10.1016/j.est.2023.108957',
 '10.1155/2023/9810102',
 '10.1155/2023/9834646',
 '10.1007/s00366-023-01859-y',
 '10.1007/978-3-642-25462-8_63',
 '10.1007/978-3-642-16493-4_54',
 '10.1007/978-3-642-05253-8_80',
 '10.1007/978-3-642-02342-2_35',
 '10.1007/978-3-642-02342-2_34',
 '10.1109/ICBMI.2011.71',
 '10.1109/EPDC.2016.7514781',
 '10.1109/ECDC.2014.6836755',
 '10.1371/journal.pone.0279589',
 '10.1007/s00500-023-08595-x',
 '10.1007/978-3-540-72530-5_15',
 '10.1080/21563306.2018.11969263',
 '10.1007/s42452-023-05300-3',
 '10.1007/s40996-019-00287-7',
 '10.21595/jve.2018.20336',
 '10.1080/15567036.2015.1024986',
 '10.1080/08839514.2014.952982',
 '10.1177/09544119221147102',
 '10.1016/j.acalib.2021.102354',
 '10.1002/dac.4792',
 '10.1016/j.eswa.2011.04.025',
 '10.1038/s41598-022-16513-8',
 '10.1007/s00500-021-06289-w',
 '10.1007/s00500-021-06289-w',
 '10.1007/s12034-022-02691-8',
 '10.1016/j.eswax.2019.100013',
 '10.1007/s11277-020-08026-2',
 'Unavailable',
 '10.1016/j.commatsci.2021.111059',
 '10.1016/j.commatsci.2021.111019',
 '10.1007/s10668-021-01761-x',
 '10.1007/978-3-642-33914-1_78',
 '10.1007/978-3-642-33914-1_78',
 '10.32047/cwb.2021.26.2.3',
 '10.1007/s00521-021-06174-5',
 '10.1007/s12665-020-09030-2',
 'unavailable',
 '10.1155/2013/212769',
 '10.1007/s00521-020-05660-6',
 '10.1007/s11069-015-1602-4',
 '10.1007/s00500-021-05597-5',
 '10.1007/s00521-020-05578-z',
 '10.1007/s00521-020-05577-0',
 '10.1007/s00521-020-05575-2',
 '10.1007/s00521-020-05576-1',
 '10.1016/j.solener.2020.09.050',
 '10.1007/s10706-019-00971-5',
 '10.1007/s00521-020-05403-7',
 '10.1007/s00521-020-05271-1',
 '10.1007/s00521-020-05301-y',
 '10.1007/s00521-020-05299-3',
 '10.1007/s00521-020-05300-z',
 '10.1007/s00521-020-05122-z',
 '10.1007/s00521-020-05120-1',
 '10.1007/s00521-020-05119-8',
 '10.1007/s00521-020-05121-0',
 '10.1007/s00521-020-05153-6',
 '10.1007/s11069-020-03924-x',
 '10.1007/s00521-020-04968-7',
 '10.1007/s00521-020-04967-8',
 '10.1016/j.compag.2020.105408',
 '10.1007/s10796-016-9716-0',
 '10.1007/s10518-020-00824-0',
 '10.1007/s00521-020-04891-x',
 '10.1007/s00521-020-04892-w',
 '10.1007/s00704-020-03152-0',
 '10.1007/s00704-020-03150-2',
 'unavailable',
 '10.1007/s11852-014-0357-5',
 '10.1007/s10845-019-01493-w',
 '10.1007/s11135-019-00948-9',
 '10.1016/j.jnca.2019.102427',
 '10.1007/s40815-019-00695-x',
 '10.1093/bioinformatics/btm094',
 '10.1007/s00477-019-01673-3',
 '10.1007/s00477-019-01674-2',
 '10.1007/s00894-019-3978-7',
 '10.1007/s12230-018-9693-6',
 '10.1007/s12665-018-7997-y',
 '10.1007/s00382-015-2730-y',
 '10.1007/s00382-018-4550-3',
 '10.1007/s12053-018-9761-2',
 '10.1007/s10479-018-3103-9',
 '10.1007/s10489-018-1367-z',
 '10.1049/iet-gtd.2018.0329',
 '10.2298/FUEE1801155E',
 '10.1007/s00521-016-2691-z',
 '10.1007/s00521-012-0984-4',
 '10.1007/s00521-010-0436-y',
 '10.1007/s00521-012-0920-7',
 '10.1007/s00521-012-0983-5',
 '10.1007/s00521-012-0986-2',
 '10.1007/s00521-012-0955-9',
 '10.1007/s00521-012-0921-6',
 '10.1155/2018/4030684',
 '10.1016/j.neucom.2013.10.015',
 '10.1016/j.apenergy.2012.11.055',
 '10.1016/j.apenergy.2012.02.078',
 '10.1080/09588221.2018.1440695',
 '10.1016/j.rinp.2021.103937',
 '10.1016/j.procs.2010.12.074',
 '10.1016/j.ins.2013.07.028',
 '10.1016/j.ins.2013.07.028',
 '10.1016/j.pnucene.2013.02.004',
 '10.1016/j.infrared.2017.11.012',
 '10.1016/j.jmsy.2016.12.004',
 '10.1109/ICEMMS.2011.6015801',
 '10.1109/ICMEE.2010.5558444',
 '10.1109/APPEEC.2010.5448778',
 '10.1109/ICACC.2010.5486987',
 '10.1109/ICMEE.2010.5558448',
 '10.1109/ICEEA.2010.5596108',
 '10.1109/ICAMS.2010.5553086',
 '10.1109/ICAMS.2010.5553281',
 '10.1109/ICAMS.2010.5552982',
 '10.1109/IC4E.2010.149',
 '10.1109/IC4E.2010.56',
 '10.1109/ICCET.2010.5485554',
 '10.1109/ICSESS.2010.5552409',
 '10.1109/ICCET.2010.5486051',
 '10.1109/ICCET.2010.5486165',
 '10.1109/ICCET.2010.5486208',
 '10.1109/ICNC.2010.5584564',
 '10.1109/ICCSIT.2010.5563890',
 '10.1109/ICCSIT.2010.5565122',
 '10.1109/ICMENS.2009.46',
 '10.1007/978-3-662-47926-1_44',
 '10.4102/sajs.v108i11/12.1107',
 '10.1016/j.joei.2016.07.001',
 '10.1007/s00366-016-0441-6',
 '10.3233/IFS-162213',
 '10.1007/978-3-319-42092-9_48',
 '10.1177/1687814017710527',
 '10.1109/ICIAFS.2007.4544787',
 '10.1109/ICCTD.2009.14',
 '10.1016/j.measurement.2018.03.048',
 '10.1109/ICIMT.2009.106',
 '10.1007/978-3-319-42092-9_48',
 '10.1016/j.jvcir.2014.05.007',
 '10.1109/ICETC.2009.12',
 '10.1142/S0219622013930012',
 '10.1016/j.compbiomed.2012.06.008']

In [17]:
import requests
import pandas as pd

# --- Existing Request Setup ---
API_KEY = "10a6fa24e6beeef124888369a691d5aa"
BASE_URL = "https://api.elsevier.com/content/search/scopus"

# List of DOIs from CSV
doi_csv = pd.read_csv(r"C:\Users\Parsa\OneDrive\Documents\Internship\Sadegh Suleimani Internship\Web Confrence\Files\retracted_compDataElec_DOI.csv")
dois = list(doi_csv["RetractionDOI"])

headers = {
    "X-ELS-APIKey": API_KEY,
    "Accept": "application/json"
}

# --- Function to Query Scopus API ---
def query_scopus_by_doi(doi):
    params = {
        "query": f"DOI({doi})",  # Query in the required format
        "view": "FULL"           # Request full record details
    }
    response = requests.get(BASE_URL, headers=headers, params=params)
    response.raise_for_status()  # Raise error if request failed
    return response.json()

# --- Request and Collect the JSON Responses ---
results = {}
for doi in dois:
    try:
        results[doi] = query_scopus_by_doi(doi)
    except Exception as e:
        print(f"Error for DOI {doi}: {e}")
        results[doi] = None

# --- Parse the Returned JSON Information ---
parsed_records = []
for doi, data in results.items():
    record = {"Queried_DOI": doi}  # Keep track of the DOI you queried
    # Check if data is valid and contains the expected keys
    if data and "search-results" in data and "entry" in data["search-results"] and data["search-results"]["entry"]:
        entry = data["search-results"]["entry"][0]  # Assume the first entry is correct

        # Extract some common fields; adjust field names as needed per the API docs.
        record["Scopus_DOI"]       = entry.get("prism:doi", None)
        record["Title"]            = entry.get("dc:title", None)
        record["Authors"]          = entry.get("dc:creator", None)
        record["PublicationName"]  = entry.get("prism:publicationName", None)
        record["CoverDate"]        = entry.get("prism:coverDate", None)
        record["AggregationType"]  = entry.get("prism:aggregationType", None)
        # You can add more fields here if required.
    else:
        record["Error"] = "No entry found or invalid response"
    parsed_records.append(record)

# --- Create a DataFrame from the Parsed Records ---
parsed_df = pd.DataFrame(parsed_records)
print(parsed_df.head())

# --- (Optional) Save the Parsed Data to a CSV File ---
parsed_df.to_csv("parsed_scopus_results.csv", index=False)
print("Parsed results saved to parsed_scopus_results.csv")

Error for DOI 10.1155/2023/9865791: 400 Client Error: Bad Request for url: https://api.elsevier.com/content/search/scopus?query=DOI%2810.1155%2F2023%2F9865791%29&view=FULL
Error for DOI 10.1155/2023/9859342: 400 Client Error: Bad Request for url: https://api.elsevier.com/content/search/scopus?query=DOI%2810.1155%2F2023%2F9859342%29&view=FULL
Error for DOI 10.1155/2023/9849356: 400 Client Error: Bad Request for url: https://api.elsevier.com/content/search/scopus?query=DOI%2810.1155%2F2023%2F9849356%29&view=FULL
Error for DOI 10.1155/2023/9831958: 400 Client Error: Bad Request for url: https://api.elsevier.com/content/search/scopus?query=DOI%2810.1155%2F2023%2F9831958%29&view=FULL
Error for DOI 10.1155/2023/9854302: 400 Client Error: Bad Request for url: https://api.elsevier.com/content/search/scopus?query=DOI%2810.1155%2F2023%2F9854302%29&view=FULL
Error for DOI 10.1007/s00779-024-01841-5: 400 Client Error: Bad Request for url: https://api.elsevier.com/content/search/scopus?query=DOI%2810.1007%2Fs00779-024-01841-5%29&view=FULL
Error for DOI 10.1155/2023/9782714: 400 Client Error: Bad Request for url: https://api.elsevier.com/content/search/scopus?query=DOI%2810.1155%2F2023%2F9782714%29&view=FULL
Error for DOI 10.1007/s00521-024-09872-y: 400 Client Error: Bad Request for url: https://api.elsevier.com/content/search/scopus?query=DOI%2810.1007%2Fs00521-024-09872-y%29&view=FULL

KeyboardInterrupt:

In [ ]:
{'opensearch:totalResults': '2', 'opensearch:startIndex': '0', 'opensearch:itemsPerPage': '2', 'opensearch:Query': {'@role': 'request', '@searchTerms': 'DOI(10.1155/2023/9865791)', '@startPage': '0'}, 'link': [{'@_fa': 'true', '@ref': 'self', '@href': 'https://api.elsevier.com/content/search/scopus?start=0&count=25&query=DOI%2810.1155%2F2023%2F9865791%29', '@type': 'application/json'}, {'@_fa': 'true', '@ref': 'first', '@href': 'https://api.elsevier.com/content/search/scopus?start=0&count=25&query=DOI%2810.1155%2F2023%2F9865791%29', '@type': 'application/json'}], 'entry': [{'@_fa': 'true', 'link': [{'@_fa': 'true', '@ref': 'self', '@href': 'https://api.elsevier.com/content/abstract/scopus_id/85214059475'}, {'@_fa': 'true', '@ref': 'author-affiliation', '@href': 'https://api.elsevier.com/content/abstract/scopus_id/85214059475?field=author,affiliation'}, {'@_fa': 'true', '@ref': 'scopus', '@href': 'https://www.scopus.com/inward/record.uri?partnerID=HzOxMe3b&scp=85214059475&origin=inward'}, {'@_fa': 'true', '@ref': 'scopus-citedby', '@href': 'https://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&scp=85214059475&origin=inward'}], 'prism:url': 'https://api.elsevier.com/content/abstract/scopus_id/85214059475', 'dc:identifier': 'SCOPUS_ID:85214059475', 'eid': '2-s2.0-85214059475', 'dc:title': 'Retracted: An Architectural Framework for Healthcare Dashboards Design', 'dc:creator': 'Healthcare Engineering J.O.', 'prism:publicationName': 'Journal of healthcare engineering', 'prism:eIssn': '20402309', 'prism:volume': '2023', 'prism:pageRange': '9865791', 'prism:coverDate': '2023-01-01', 'prism:coverDisplayDate': '2023', 'prism:doi': '10.1155/2023/9865791', 'citedby-count': '0', 'pubmed-id': '37946909', 'prism:aggregationType': 'Journal', 'subtype': 'er', 'subtypeDescription': 'Erratum', 'source-id': '21100205972', 'openaccess': '1', 'openaccessFlag': True, 'freetoread': {'value': [{'$': 'all'}, {'$': 'publisherfullgold'}, {'$': 'repository'}, {'$': 'repositoryvor'}]}, 'freetoreadLabel': {'value': [{'$': 'All Open Access'}, {'$': 'Gold'}, {'$': 'Green'}]}}, {'@_fa': 'true', 'link': [{'@_fa': 'true', '@ref': 'self', '@href': 'https://api.elsevier.com/content/abstract/scopus_id/85180148129'}, {'@_fa': 'true', '@ref': 'author-affiliation', '@href': 'https://api.elsevier.com/content/abstract/scopus_id/85180148129?field=author,affiliation'}, {'@_fa': 'true', '@ref': 'scopus', '@href': 'https://www.scopus.com/inward/record.uri?partnerID=HzOxMe3b&scp=85180148129&origin=inward'}, {'@_fa': 'true', '@ref': 'scopus-citedby', '@href': 'https://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&scp=85180148129&origin=inward'}], 'prism:url': 'https://api.elsevier.com/content/abstract/scopus_id/85180148129', 'dc:identifier': 'SCOPUS_ID:85180148129', 'eid': '2-s2.0-85180148129', 'dc:title': 'Retraction: An Architectural Framework for Healthcare Dashboards Design (Journal of Healthcare Engineering (2021) 2021 (1964054) DOI: 10.1155/2021/1964054)', 'prism:publicationName': 'Journal of Healthcare Engineering', 'prism:issn': '20402295', 'prism:eIssn': '20402309', 'prism:volume': '2023', 'prism:pageRange': None, 'prism:coverDate': '2023-01-01', 'prism:coverDisplayDate': '2023', 'prism:doi': '10.1155/2023/9865791', 'citedby-count': '0', 'pubmed-id': '37946909', 'prism:aggregationType': 'Journal', 'subtype': 'er', 'subtypeDescription': 'Erratum', 'article-number': '9865791', 'source-id': '21100205972', 'openaccess': '1', 'openaccessFlag': True, 'freetoread': {'value': [{'$': 'all'}, {'$': 'publisherfullgold'}, {'$': 'repository'}, {'$': 'repositoryvor'}]}, 'freetoreadLabel': {'value': [{'$': 'All Open Access'}, {'$': 'Gold'}, {'$': 'Green'}]}}]}