In [54]:
import pandas as pd
doi_df = pd.read_csv(r"C:\Users\Parsa\OneDrive\Documents\Internship\Sadegh Suleimani Internship\Web Confrence\Files\retracted_compDataElec_DOI.csv")

In [55]:
doi_list = list(doi_df["RetractionDOI"])

In [56]:
len(doi_list)

166

In [18]:
compDf = pd.read_csv(r"C:\Users\Parsa\Downloads\Merged_Retraction___Citation_Data.csv")

In [20]:
compDf.iloc[56]

Unnamed: 0                                                              56
Record ID                                                            34050
Title_x                  Client-server, psychoacoustic communication fo...
Subject                                            (B/T) Computer Science;
Institution                          Islamic Azad Univ. Karaj, Karaj, Iran
Journal                  2010 International Conference on Information, ...
Publisher                IEEE: Institute of Electrical and Electronics ...
Country                                                               Iran
Author                                                          E Ramezani
URLS                     http://retractionwatch.com/?s=Scigen;http://re...
ArticleType                                     Conference Abstract/Paper;
RetractionDate                                               1/1/2021 0:00
RetractionDOI                                                  Unavailable
RetractionPubMedID                                                     0.0
OriginalPaperDate                                          10/18/2010 0:00
OriginalPaperDOI                                10.1109/ICINA.2010.5636687
OriginalPaperPubMedID                                                  0.0
RetractionNature                                                Retraction
Reason                   +Date of Retraction/Other Unknown;+Investigati...
Paywalled                                                               No
Notes                    See also: https://asistdl.onlinelibrary.wiley....
DOI                                                                    NaN
Title_y                                                                NaN
OpenAlex ID                                                            NaN
Cited By                                                               NaN
References                                                             NaN
Name: 56, dtype: object

In [21]:
compDf.iloc[67]

Unnamed: 0                                                              67
Record ID                                                            26427
Title_x                  The Stability of Gauss Model Having One-Prey a...
Subject                  (B/T) Data Science;(BLS) Zoology;(PHY) Mathema...
Institution              Department of Mathematics, Razi University, Ke...
Journal                  Journal of Nonlinear Analysis and Optimization...
Publisher                Center of Excellence in Nonlinear Analysis and...
Country                                                        Iran;Turkey
Author                   Ali Farajzadeh;Mohammad Hossen Rahmani Doust;F...
URLS                                                                   NaN
ArticleType                                              Research Article;
RetractionDate                                              5/22/2013 0:00
RetractionDOI                                                  unavailable
RetractionPubMedID                                                     0.0
OriginalPaperDate                                          12/11/2011 0:00
OriginalPaperDOI                                               unavailable
OriginalPaperPubMedID                                                  0.0
RetractionNature                                                Retraction
Reason                                                     +Error in Text;
Paywalled                                                               No
Notes                                                                  NaN
DOI                                                                    NaN
Title_y                                                                NaN
OpenAlex ID                                                            NaN
Cited By                                                               NaN
References                                                             NaN
Name: 67, dtype: object

In [22]:
compDf.iloc[98]

Unnamed: 0                                                              98
Record ID                                                            22232
Title_x                  The relationship between creativity and academ...
Subject                  (B/T) Computer Science;(SOC) Education;(SOC) S...
Institution              Associate Professor, Department of Education S...
Journal                        Journal of Fundamental and Applied Sciences
Publisher                                            University of El Qued
Country                                                               Iran
Author                               M Sobhaninejad;M H Tajdary;K Esmaeili
URLS                     http://retractionwatch.com/2019/02/20/journal-...
ArticleType                                     Conference Abstract/Paper;
RetractionDate                                              12/1/2018 0:00
RetractionDOI                                                  unavailable
RetractionPubMedID                                                     0.0
OriginalPaperDate                                            3/7/2018 0:00
OriginalPaperDOI                                   10.4314/jfas.v10i6s.153
OriginalPaperPubMedID                                                  0.0
RetractionNature                                                Retraction
Reason                   +Notice - Limited or No Information;+Removed;+...
Paywalled                                                               No
Notes                                                                  NaN
DOI                                                                    NaN
Title_y                                                                NaN
OpenAlex ID                                                            NaN
Cited By                                                               NaN
References                                                             NaN
Name: 98, dtype: object

In [25]:
wos2 = pd.read_csv(r"C:\Users\Parsa\OneDrive\Documents\Internship\Sadegh Suleimani Internship\Web Confrence\hezhWebofScience\savedrecs2.csv")

In [26]:
wos1 = pd.read_csv(r"C:\Users\Parsa\OneDrive\Documents\Internship\Sadegh Suleimani Internship\Web Confrence\hezhWebofScience\savedrecs.csv")

In [30]:
counter = 0
for index, row in wos1.iterrows():
    for index2, row2 in wos2.iterrows():
        if row['DOI'] != row2['DOI']:
            continue
        else:
            counter = counter + 1
            print(index,index2)

17 0
18 1
19 2
20 3
21 4
22 5
26 6
27 7
28 8
29 9
30 10
31 11
32 12
33 13
36 14
37 15
38 16
39 17
40 18
41 19
42 20
43 21
44 22
45 23
46 24
47 25
48 26
49 27

In [31]:
counter

28

In [32]:
compDf

,Unnamed: 0,Record ID,Title_x,Subject,Institution,Journal,Publisher,Country,Author,URLS,...,OriginalPaperPubMedID,RetractionNature,Reason,Paywalled,Notes,DOI,Title_y,OpenAlex ID,Cited By,References
0,0,60949,An Architectural Framework for Healthcare Dash...,(B/T) Data Science;(B/T) Technology;(HSC) Medi...,"Faculty of Management, University of Tehran, T...",Journal of Healthcare Engineering,Hindawi,Iran,Saeed Rouhani;Shooka Zamenian,https://retractionwatch.com/2022/09/28/exclusi...,...,34745492.0,Retraction,+Concerns/Issues About Data;+Concerns/Issues A...,No,NaN,10.1155/2023/9865791,Retracted: An Architectural Framework for Heal...,https://openalex.org/W4388124931,[],['https://openalex.org/W3210178340']
1,1,60474,Clustering of Brain Tumor Based on Analysis of...,(B/T) Computer Science;(B/T) Technology;(HSC) ...,"Department of Industrial Engineering, Islamic ...",BioMed Research International,Hindawi,Iran,Ali Hamzenejad;Saeid Jafarzadeh Ghoushchi;Vahi...,https://retractionwatch.com/2022/09/28/exclusi...,...,34504897.0,Retraction,+Fake Peer Review;+Investigation by Journal/Pu...,No,NaN,10.1155/2023/9859342,Retracted: Clustering of Brain Tumor Based on ...,https://openalex.org/W4389127150,[],['https://openalex.org/W3198441341']
2,2,60249,Using a Blur Metric to Estimate Linear Motion ...,(B/T) Computer Science;(HSC) Radiology/Imaging;,"Computer Science Department, Faculty of Mathem...",Computational and Mathematical Methods in Medi...,Hindawi,Iran,Taiebeh Askari Javaran;Hamid Hassanpour,https://retractionwatch.com/2022/09/28/exclusi...,...,34745327.0,Retraction,+Fake Peer Review;+Investigation by Journal/Pu...,No,NaN,10.1155/2023/9849356,Retracted: Using a Blur Metric to Estimate Lin...,https://openalex.org/W4389381587,[],['https://openalex.org/W3210201227']
3,3,60044,Method of Cumulative Anomaly Identification fo...,(B/T) Computer Science;(B/T) Technology;,"Shaoxing University Yuanpei College, Shaoxing ...",Security and Communication Networks,Hindawi,China;Iran,Zhiying Xu;Ting Yang;Moslem Lari Najafi,https://retractionwatch.com/2022/09/28/exclusi...,...,0.0,Retraction,+Fake Peer Review;+Investigation by Journal/Pu...,No,NaN,10.1155/2023/9831958,Retracted: Method of Cumulative Anomaly Identi...,https://openalex.org/W4389371056,[],['https://openalex.org/W4220766059']
4,4,59716,A Computer-Aided Method for Digestive System A...,(B/T) Data Science;(B/T) Technology;(HSC) Medi...,"Image Processing and Data Mining Lab, Shahrood...",Journal of Healthcare Engineering,Hindawi,France;Iran,Zahra Amiri;Hamid Hassanpour;Azeddine Beghdadi,https://retractionwatch.com/2022/09/28/exclusi...,...,34707798.0,Retraction,+Fake Peer Review;+Investigation by Journal/Pu...,No,NaN,10.1155/2023/9854302,Retracted: A Computer‐Aided Method for Digesti...,https://openalex.org/W4389398875,[],['https://openalex.org/W3206639986']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,172,7034,A Novel Voting Mathematical Rule Classificatio...,(B/T) Computer Science;(PHY) Mathematics;,"Department of Computer Engineering, Iran Healt...",Lecture Notes in Computer Science,Springer,Iran,Sadrollah Abbasi;Afshin Shahriari;Yaser Nemati,NaN,...,NaN,Retraction,+Plagiarism of Article;,No,International Conference on Computational Scie...,10.1007/978-3-319-42092-9_48,Retraction Note to: A Novel Voting Mathematica...,https://openalex.org/W2563871704,[],[]
173,173,7031,Pose invariant face recognition using biologic...,(B/T) Computer Science;(B/T) Data Science;,"Faculty of Electrical Engineering, Iran Univer...",Journal of Visual Communication and Image Repr...,Elsevier,Iran,Masoud Ghaderi Dehkordi;Mohammad Reza Daliri;A...,http://retractionwatch.com/2015/06/22/plagiari...,...,0.0,Retraction,+Breach of Policy by Author;+Plagiarism of Art...,No,NaN,10.1016/j.jvcir.2014.05.007,Retraction Note to “Pose invariant face recogn...,https://openalex.org/W2052373026,[],[]
174,174,6929,Fuzzy PID Sliding Mode Controller Design for t...,(B/T) Computer Science;(B/T) Technology;(PHY) ...,"Department of Mechatronics Engineering, Semnan...",2009 International Conference on Education Tec...,IEEE: Institute of Electrical and Electronics ...,Iran,Mohsen Fallahi;Sassan Azadi,https://retractionwatch.com/2015/06/25/one-pub...,...,0.0,Retraction,+Breach of Policy by Author;+Date of Retractio...,No,"Date of retraction unknown, estimated from con...",10.1109/ICETC.2009.12,Notice of Retraction: Fuzzy PID Sliding Mode C...,https://openalex.org/W1961499357,[],"['https://openalex.org/W11567962', 'https://op..."
175,175,5610,A Lagrangian-based Solution Algorithm for Stra...,(B/T) Business - Marketing;(B/T) Computer Scie...,"Department of Industrial Engineering, Amirkabi...",International Journal of Information Technolog...,World Scientific Publishing Company,Iran,G Reza Nasiri;Hamid Davoudpour;Behrooz Karimi,NaN,...,0.0,Retraction,+Duplication of Article;,Yes,NaN,10.1142/S0219622013930012,STATEMENT OF RETRACTION — A LAGRANGIAN-BASED S...,https://openalex.org/W2075085261,[],[]
176,176,4600,A novel real-time patient-specific seizure dia...,(B/T) Computer Science;(HSC) Radiology/Imaging;,"Department of Electrical Engineering, Najafaba...",Computers in Biology and Medicine,Elsevier,Iran,Saadat Nasehi;Hossein Pourghassem,http://retractionwatch.com/2013/01/17/note-to-...,...,22795227.0,Retraction,+Concerns/Issues About Results;+Plagiarism of ...,No,NaN,10.1016/j.compbiomed.2012.06.008,RETRACTED: A novel real-time patient-specific ...,https://openalex.org/W2162816509,[],"['https://openalex.org/W1556131344', 'https://..."

In [57]:
hezh2 = pd.read_csv(r"C:\Users\Parsa\OneDrive\Documents\Internship\Sadegh Suleimani Internship\Web Confrence\hezh2\savedrecs.csv")

In [58]:
for index, row in hezh2.iterrows():
    if row['DOI'] not in doi_list:
        print(index)

26
34
109
110
112

In [60]:
hezh2[hezh2.duplicated(keep=False)]

,Publication Type,Authors,Book Authors,Book Editors,Book Group Authors,Author Full Names,Book Author Full Names,Group Authors,Article Title,Source Title,...,Web of Science Index,Research Areas,IDS Number,Pubmed Id,Open Access Designations,Highly Cited Status,Hot Paper Status,Date of Export,UT (Unique WOS ID),Web of Science Record
20,J,"Kanimozhi, U; Sannasi, G; Manjula, D; Arputhar...",NaN,NaN,NaN,"Kanimozhi, U.; Sannasi, Ganapathy; Manjula, D....",NaN,NaN,RETRACTED: A user preference tree based person...,SOFT COMPUTING,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,YM6GT,NaN,Bronze,NaN,NaN,2025-02-08,WOS:000705718100002,View Full Record in Web of Science
26,J,"Nazari, A",NaN,NaN,NaN,"Nazari, Ali",NaN,NaN,RETRACTION: Computer-aided prediction of physi...,CEMENT WAPNO BETON,...,Science Citation Index Expanded (SCI-EXPANDED),Construction & Building Technology; Materials ...,SS6LC,NaN,Bronze,NaN,NaN,2025-02-08,WOS:000661865000001,View Full Record in Web of Science
34,J,"Li, ZX; Jamshidian, M; Mousavi, S; Karimipour,...",NaN,NaN,NaN,"Li, Zhixiong; Jamshidian, Morteza; Mousavi, Sa...",NaN,NaN,RETRACTED: Develop a numerical approach of fuz...,INTERNATIONAL JOURNAL OF NUMERICAL METHODS FOR...,...,Science Citation Index Expanded (SCI-EXPANDED),Thermodynamics; Mathematics; Mechanics,RV1OT,NaN,NaN,NaN,NaN,2025-02-08,WOS:000598029300001,View Full Record in Web of Science
91,J,"Fard, OS; Salahshour, S; Dizicheh, AK",NaN,NaN,NaN,"Fard, Omid Solaymani; Salahshour, S.; Dizicheh...",NaN,NaN,Numerical solutions for linear system of first...,INFORMATION SCIENCES,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,252JP,NaN,NaN,NaN,NaN,2025-02-08,WOS:000327001300014,View Full Record in Web of Science
108,J,"Kanimozhi, U; Sannasi, G; Manjula, D; Arputhar...",NaN,NaN,NaN,"Kanimozhi, U.; Sannasi, Ganapathy; Manjula, D....",NaN,NaN,RETRACTED: A user preference tree based person...,SOFT COMPUTING,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,YM6GT,NaN,Bronze,NaN,NaN,2025-02-08,WOS:000705718100002,View Full Record in Web of Science
109,J,"Nazari, A",NaN,NaN,NaN,"Nazari, Ali",NaN,NaN,RETRACTION: Computer-aided prediction of physi...,CEMENT WAPNO BETON,...,Science Citation Index Expanded (SCI-EXPANDED),Construction & Building Technology; Materials ...,SS6LC,NaN,Bronze,NaN,NaN,2025-02-08,WOS:000661865000001,View Full Record in Web of Science
110,J,"Li, ZX; Jamshidian, M; Mousavi, S; Karimipour,...",NaN,NaN,NaN,"Li, Zhixiong; Jamshidian, Morteza; Mousavi, Sa...",NaN,NaN,RETRACTED: Develop a numerical approach of fuz...,INTERNATIONAL JOURNAL OF NUMERICAL METHODS FOR...,...,Science Citation Index Expanded (SCI-EXPANDED),Thermodynamics; Mathematics; Mechanics,RV1OT,NaN,NaN,NaN,NaN,2025-02-08,WOS:000598029300001,View Full Record in Web of Science
111,J,"Fard, OS; Salahshour, S; Dizicheh, AK",NaN,NaN,NaN,"Fard, Omid Solaymani; Salahshour, S.; Dizicheh...",NaN,NaN,Numerical solutions for linear system of first...,INFORMATION SCIENCES,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,252JP,NaN,NaN,NaN,NaN,2025-02-08,WOS:000327001300014,View Full Record in Web of Science

In [40]:
for index, row in hezh2.iterrows():
    if row['DOI'] in doi_list:
        doi_list.remove(row['DOI'])

In [42]:
len(doi_list)

61

In [44]:
remainderDOI = ' OR '.join(doi_list)

In [45]:
remainderDOI

'10.1155/2023/9865791 OR 10.1155/2023/9849356 OR 10.1155/2023/9831958 OR 10.1155/2023/9854302 OR 10.1007/s00779-024-01841-5 OR 10.1155/2023/9782714 OR 10.1007/s00521-024-09872-y OR 10.1155/2023/9814037 OR 10.1155/2023/9801974 OR 10.1155/2023/9872579 OR 10.1155/2023/9826862 OR 10.1108/hff-01-2019-0019 OR 10.1007/978-3-540-69905-7_71 OR 10.1155/2023/9810102 OR 10.1155/2023/9834646 OR 10.1007/978-3-642-25462-8_63 OR 10.1007/978-3-642-16493-4_54 OR 10.1007/978-3-642-05253-8_80 OR 10.1007/978-3-642-02342-2_35 OR 10.1007/978-3-642-02342-2_34 OR 10.1109/ICBMI.2011.71 OR 10.1109/EPDC.2016.7514781 OR 10.1109/ECDC.2014.6836755 OR 10.1007/978-3-540-72530-5_15 OR 10.1080/21563306.2018.11969263 OR 10.1080/15567036.2015.1024986 OR 10.1007/s00500-021-06289-w OR 10.1016/j.eswax.2019.100013 OR 10.1007/978-3-642-33914-1_78 OR 10.1007/978-3-642-33914-1_78 OR 10.32047/cwb.2021.26.2.3 OR 10.1155/2013/212769 OR 10.1007/s10706-019-00971-5 OR 10.1007/s11135-019-00948-9 OR 10.1007/s00521-012-0984-4 OR 10.1007/s00521-010-0436-y OR 10.1007/s00521-012-0920-7 OR 10.1007/s00521-012-0983-5 OR 10.1007/s00521-012-0986-2 OR 10.1007/s00521-012-0955-9 OR 10.1007/s00521-012-0921-6 OR 10.1016/j.ins.2013.07.028 OR 10.1109/ICEMMS.2011.6015801 OR 10.1109/ICMEE.2010.5558444 OR 10.1109/ICMEE.2010.5558448 OR 10.1109/ICEEA.2010.5596108 OR 10.1109/ICAMS.2010.5553086 OR 10.1109/ICAMS.2010.5553281 OR 10.1109/ICAMS.2010.5552982 OR 10.1109/ICCET.2010.5485554 OR 10.1109/ICSESS.2010.5552409 OR 10.1109/ICCET.2010.5486051 OR 10.1109/ICCET.2010.5486165 OR 10.1109/ICCET.2010.5486208 OR 10.1109/ICNC.2010.5584564 OR 10.1109/ICCSIT.2010.5563890 OR 10.1109/ICCSIT.2010.5565122 OR 10.1109/ICMENS.2009.46 OR 10.1007/978-3-662-47926-1_44 OR 10.1007/978-3-319-42092-9_48 OR 10.1007/978-3-319-42092-9_48'

In [46]:
remainderRes = ['10.1007/s00500-021-06289-w'
,'10.32047/CWB.2021.26.2.3'
,'10.1108/HFF-01-2019-0019'
,'10.1016/j.ins.2013.07.028'
]

In [47]:
for item in remainderRes:
    if item in doi_list:
        doi_list.remove(item)

In [48]:
len(doi_list)

59

In [49]:
remainderDOI2 = ' OR '.join(doi_list)

In [50]:
remainderDOI2

'10.1155/2023/9865791 OR 10.1155/2023/9849356 OR 10.1155/2023/9831958 OR 10.1155/2023/9854302 OR 10.1007/s00779-024-01841-5 OR 10.1155/2023/9782714 OR 10.1007/s00521-024-09872-y OR 10.1155/2023/9814037 OR 10.1155/2023/9801974 OR 10.1155/2023/9872579 OR 10.1155/2023/9826862 OR 10.1108/hff-01-2019-0019 OR 10.1007/978-3-540-69905-7_71 OR 10.1155/2023/9810102 OR 10.1155/2023/9834646 OR 10.1007/978-3-642-25462-8_63 OR 10.1007/978-3-642-16493-4_54 OR 10.1007/978-3-642-05253-8_80 OR 10.1007/978-3-642-02342-2_35 OR 10.1007/978-3-642-02342-2_34 OR 10.1109/ICBMI.2011.71 OR 10.1109/EPDC.2016.7514781 OR 10.1109/ECDC.2014.6836755 OR 10.1007/978-3-540-72530-5_15 OR 10.1080/21563306.2018.11969263 OR 10.1080/15567036.2015.1024986 OR 10.1016/j.eswax.2019.100013 OR 10.1007/978-3-642-33914-1_78 OR 10.1007/978-3-642-33914-1_78 OR 10.32047/cwb.2021.26.2.3 OR 10.1155/2013/212769 OR 10.1007/s10706-019-00971-5 OR 10.1007/s11135-019-00948-9 OR 10.1007/s00521-012-0984-4 OR 10.1007/s00521-010-0436-y OR 10.1007/s00521-012-0920-7 OR 10.1007/s00521-012-0983-5 OR 10.1007/s00521-012-0986-2 OR 10.1007/s00521-012-0955-9 OR 10.1007/s00521-012-0921-6 OR 10.1109/ICEMMS.2011.6015801 OR 10.1109/ICMEE.2010.5558444 OR 10.1109/ICMEE.2010.5558448 OR 10.1109/ICEEA.2010.5596108 OR 10.1109/ICAMS.2010.5553086 OR 10.1109/ICAMS.2010.5553281 OR 10.1109/ICAMS.2010.5552982 OR 10.1109/ICCET.2010.5485554 OR 10.1109/ICSESS.2010.5552409 OR 10.1109/ICCET.2010.5486051 OR 10.1109/ICCET.2010.5486165 OR 10.1109/ICCET.2010.5486208 OR 10.1109/ICNC.2010.5584564 OR 10.1109/ICCSIT.2010.5563890 OR 10.1109/ICCSIT.2010.5565122 OR 10.1109/ICMENS.2009.46 OR 10.1007/978-3-662-47926-1_44 OR 10.1007/978-3-319-42092-9_48 OR 10.1007/978-3-319-42092-9_48'

In [51]:
remainderRes2 = ['10.32047/CWB.2021.26.2.3'
,'10.1108/HFF-01-2019-0019'
]

In [52]:
for item in remainderRes2:
    if item in doi_list:
        doi_list.remove(item)

In [53]:
len(doi_list)

59